# Analyse Exploratoire des Données (EDA) -RGPH 2024 Dataset

## Description générale sur dataset

Le dataset RGPH 2024 contient les résultats du Recensement Général de la Population et de l'Habitat au Maroc. Il est structuré en **6 feuilles Excel**, réparties selon deux grands axes : **population** et **ménages**, et selon le **milieu de résidence** (urbain, rural, général).

---
##  Résumé des Feuilles

| Nom du Tableau        | Type de Données | Milieu       |
|-----------------------|------------------|--------------|
| Population_Générale   | Population        | Général      |
| Population_Urbaine    | Population        | Urbain       |
| Population_Rurale     | Population        | Rural        |
| Ménages_Général       | Ménages / Logement| Général      |
| Ménages_Urbains       | Ménages / Logement| Urbain       |
| Ménages_Ruraux        | Ménages / Logement| Rural        |

---

##  Variables dans les Tableaux **Population**

### 1. Démographie

- Population légale (dans "ensemble" uniquement)
- Population municipale
- Répartition par sexe (%)
- Répartition par âge quinquennal (%)
- État matrimonial des 15 ans et plus (%)
  - Célibataire
  - Marié.e
  - Divorcé.e
  - Veuf.ve
- Âge moyen au mariage
- Indicateur conjoncturel de fécondité
- Taux de prévalence du handicap

### 2. Éducation

- Population de 7-12 ans (%)
- Taux de scolarisation des 6-11 ans (%)
- Population de 10 ans et plus
- Taux d’analphabétisme des 10 ans et plus (%)
- Taux d’analphabétisme des 15 ans et plus (%)
- Population alphabète de 10 ans et plus
- Langues lues et écrites (%) :
  - Arabe
  - Amazigh (Tifinagh)
  - Anglais
  - Français
- Niveau d'études (%) :
  - Aucun niveau
  - Préscolaire
  - Primaire
  - Secondaire collégial
  - Secondaire qualifiant
  - Supérieur
- Langues locales utilisées (%) :
  - Darija
  - Tachelhit
  - Tamazight
  - Tarifit
  - Hassania

### 3. Emploi / Économie

- Population de 15 ans et plus
- Population active de 15 ans et plus
- Population inactive de 15 ans et plus
- Taux d'activité des 15 ans et plus (%)
- Taux de chômage (%)
- Population active occupée de 15 ans et plus
- Statut professionnel (%) :
  - Employeur
  - Indépendant
  - Salarié secteur public
  - Salarié secteur privé
  - Aide familiale
  - Apprenti
  - Coopérateur / Associé
  - Autres

---

## Variables dans les Tableaux **Ménages**

### 1. Informations de base

- Population municipale
- Nombre de ménages
- Taille moyenne des ménages
- Nombre de ménages sédentaires

### 2. Type de logement (%)

- Villa / étage de villa
- Appartement
- Maison marocaine
- Maison sommaire / bidonville
- Logement rural
- Autre

### 3. Conditions de vie

- Nombre moyen de personnes par pièce
- Statut d’occupation du logement (%) :
  - Propriétaire
  - Locataire
  - Autre
- Âge du logement (%) :
  - Moins de 10 ans
  - 10-19 ans
  - 20-49 ans
  - 50 ans ou plus

### 4. Équipements de confort (%)

- Cuisine
- W.C
- Pièce d’eau
- Électricité
- Eau courante

### 5. Infrastructure & environnement

- Mode d’évacuation des eaux usées (%) :
  - Réseau public
  - Fosse septique
  - Autre
- Mode d’évacuation des déchets ménagers (%) :
  - Bac à ordures communal
  - Camion communal / privé
  - Nature
  - Autres
- Combustible utilisé pour la cuisson (%) :
  - Électricité
  - Gaz
  - Charbon
  - Bois énergie
  - Autre
- Distance moyenne au goudron (km)

---

In [ ]:
# Importation des bibliothèques nécessaires
import pandas as pd
import numpy as np

## 1. Chargement et aperçu initial des données

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Indicateurs démographiques et socioéconomiques du Royaume du Maroc selon les résultats du RGPH 2024.xlsx to Indicateurs démographiques et socioéconomiques du Royaume du Maroc selon les résultats du RGPH 2024 (1).xlsx

In [ ]:
RGPH2024= pd.ExcelFile("Indicateurs démographiques et socioéconomiques du Royaume du Maroc selon les résultats du RGPH 2024.xlsx")
print(RGPH2024.sheet_names)

['Population', 'Population_Urbaine', 'Population_Rurale', 'Ménages', 'Ménages_Urbains', 'Ménages_Ruraux', 'Définitions_des_Concepts', 'Signes_Conventionnels', 'Avis_aux_Utilisateurs']

In [ ]:
# Chargement des différentes feuilles du fichier Excel
population_totale = pd.read_excel(RGPH2024, sheet_name="Population")
population_urbaine = pd.read_excel(RGPH2024, sheet_name="Population_Urbaine")
population_rurale = pd.read_excel(RGPH2024, sheet_name="Population_Rurale")
menages = pd.read_excel(RGPH2024, sheet_name="Ménages")
menages_urbains = pd.read_excel(RGPH2024, sheet_name="Ménages_Urbains")
menages_ruraux = pd.read_excel(RGPH2024, sheet_name="Ménages_Ruraux")

In [ ]:
population_totale
#!!!problème d'affichage des données

,Milieu de résidence : Ensemble,Unnamed: 1,Sexe : Ensemble,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 181,Unnamed: 182,Unnamed: 183,Unnamed: 184,Unnamed: 185,Unnamed: 186,Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190
0,NaN,NaN,Population légale,Population municipale,Sexe (%),NaN,Âge quinquennal (%),NaN,NaN,NaN,...,Taux de chômage (%),Population active occupée de 15 ans et plus,Statut professionnel des actifs occupés de 15 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Code géographique,Collectivités territoriales,NaN,NaN,Masculin,Féminin,0-4 ans,5-9 ans,10-14 ans,15-19 ans,...,NaN,NaN,Employeur,Indépendant,Salarié du secteur public,Salarié du secteur privé,Aide familial,Apprenti,Coopérateur/Associé,Autre
2,NaN,Ensemble du territoire national,36828330,36490591,49.9,50.1,7.6,9.3,9.6,8.2,...,25.9,1696785,1.7,11.2,21.7,58.8,2.8,0.4,0.9,2.4
3,1,Région de Tanger-Tétouan-Al Hoceima,4030222,4008655,50.8,49.2,8.2,9.6,9.4,7.9,...,23,232294,1.3,11.3,15.4,62.3,7,0.3,0.9,1.6
4,1511,Préfecture de Tanger-Assilah,1494413,1487236,50.8,49.2,8.5,9.4,8.8,7.4,...,17.8,127760,1.5,7.4,10.5,77.1,1.3,0.3,0.7,1.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014,1206603,Cercle d'Aousserd,12188,2010,56,44,9.4,10,8.8,6.9,...,21.8,97,1,9.3,17.5,62.9,6.2,0,0,3.1
2015,120660305,Commune d'Aousserd,3855,273,76.2,23.8,3.3,2.6,6.2,2.6,...,10,9,0,11.1,22.2,0,55.6,0,0,11.1
2016,120660303,Commune d'Aghouinite*,1006,1006,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
2017,120660309,Commune de Zoug*,592,592,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
2018,120660307,Commune de Tichla,6735,139,57.6,42.4,17.3,12.2,7.9,6.5,...,50,1,0,0,100,0,0,0,0,0

In [ ]:
population_totale = pd.read_excel(RGPH2024, sheet_name="Population", header=[0,1,2])
population_totale

     Milieu de résidence : Ensemble                                       \
                 Unnamed: 0_level_1                   Unnamed: 1_level_1
                  Code géographique          Collectivités territoriales
0                               NaN      Ensemble du territoire national
1                               1.0  Région de Tanger-Tétouan-Al Hoceima
2                            1511.0         Préfecture de Tanger-Assilah
3                         1511010.0                    Commune de Tanger
4                        15110105.0            Arrondissement de Mghogha
...                             ...                                  ...
2012                      1206603.0                    Cercle d'Aousserd
2013                    120660305.0                   Commune d'Aousserd
2014                    120660303.0                Commune d'Aghouinite*
2015                    120660309.0                     Commune de Zoug*
2016                    120660307.0                    Commune de Tichla

        Sexe : Ensemble                                         \
      Population légale Population municipale Sexe (%)
     Unnamed: 2_level_2    Unnamed: 3_level_2 Masculin Féminin
0              36828330              36490591     49.9    50.1
1               4030222               4008655     50.8    49.2
2               1494413               1487236     50.8    49.2
3               1275428               1272718     50.6    49.4
4                252656                252177     50.8    49.2
...                 ...                   ...      ...     ...
2012              12188                  2010       56      44
2013               3855                   273     76.2    23.8
2014               1006                  1006        .       .
2015                592                   592        .       .
2016               6735                   139     57.6    42.4

                                                      ...  \
     Âge quinquennal (%)                              ...
                 0-4 ans 5-9 ans 10-14 ans 15-19 ans  ...
0                    7.6     9.3       9.6       8.2  ...
1                    8.2     9.6       9.4       7.9  ...
2                    8.5     9.4       8.8       7.4  ...
3                    8.3     9.2       8.6       7.4  ...
4                    8.2     9.3         9       7.6  ...
...                  ...     ...       ...       ...  ...
2012                 9.4      10       8.8       6.9  ...
2013                 3.3     2.6       6.2       2.6  ...
2014                   .       .         .         .  ...
2015                   .       .         .         .  ...
2016                17.3    12.2       7.9       6.5  ...

           Sexe : Féminin                                              \
      Taux de chômage (%) Population active occupée de 15 ans et plus
     Unnamed: 181_level_2                        Unnamed: 182_level_2
0                    25.9                                     1696785
1                      23                                      232294
2                    17.8                                      127760
3                    17.7                                      114125
4                      20                                       21357
...                   ...                                         ...
2012                 21.8                                          97
2013                   10                                           9
2014                    .                                           .
2015                    .                                           .
2016                   50                                           1

                                                                    \
     Statut professionnel des actifs occupés de 15 ans et plus (%)
                                                         Employeur
0                                                   1.7
1                                                   1.3
2                                                   1.5
3                                                   1.5
4                                                   1.4
...                                                 ...
2012                                                  1
2013                                                  0
2014                                                  .
2015                                                  .
2016                                                  0

                                                                     \

     Indépendant Salarié du secteur public Salarié du secteur privé
0           11.2                      21.7                     58.8
1           11.3                      15.4                     62.3
2            7.4                      10.5                     77.1
3            6.8                      10.4                     78.4
4            6.5                       7.7                     81.2
...          ...                       ...                      ...
2012         9.3                      17.5                     62.9
2013        11.1                      22.2                        0
2014           .                         .                        .
2015           .                         .                        .
2016           0                       100                        0



     Aide familial Apprenti Coopérateur/Associé Autre
0              2.8      0.4                 0.9   2.4
1                7      0.3                 0.9   1.6
2              1.3      0.3                 0.7   1.3
3              0.7      0.3                 0.7   1.3
4              0.7      0.2                 0.7   1.6
...            ...      ...                 ...   ...
2012           6.2        0                   0   3.1
2013          55.6        0                   0  11.1
2014             .        .                   .     .
2015             .        .                   .     .
2016             0        0                   0     0

[2017 rows x 191 columns]

In [ ]:

RGPH2024 = pd.ExcelFile("Indicateurs démographiques et socioéconomiques du Royaume du Maroc selon les résultats du RGPH 2024.xlsx")

# Function to clean MultiIndex columns (fix Unnamed, NaN)
def clean_multilevel_columns(df):
    new_cols = []
    for col in df.columns:
        clean_col = tuple(
            "" if ("Unnamed" in str(c) or pd.isna(c)) else str(c).strip()
            for c in col
        )
        new_cols.append(clean_col)
    df.columns = pd.MultiIndex.from_tuples(new_cols)
    return df


def forward_fill_column_levels(df):
    df.columns = pd.MultiIndex.from_tuples([
        tuple(pd.Series(col).ffill()) for col in df.columns
    ])
    return df

# Read sheets with 3 header rows
population_totale = pd.read_excel(RGPH2024, sheet_name="Population", header=[0,1,2])
population_urbaine = pd.read_excel(RGPH2024, sheet_name="Population_Urbaine", header=[0,1,2])
population_rurale = pd.read_excel(RGPH2024, sheet_name="Population_Rurale", header=[0,1,2])

# Clean and fix headers
population_totale = clean_multilevel_columns(population_totale)
population_totale = forward_fill_column_levels(population_totale)

population_urbaine = clean_multilevel_columns(population_urbaine)
population_urbaine = forward_fill_column_levels(population_urbaine)

population_rurale = clean_multilevel_columns(population_rurale)
population_rurale = forward_fill_column_levels(population_rurale)

# Check columns for population total
for col in population_totale.columns:
    print(col)

('Milieu de résidence : Ensemble', '', 'Code géographique')
('Milieu de résidence : Ensemble', '', 'Collectivités territoriales')
('Sexe : Ensemble', 'Population légale', '')
('Sexe : Ensemble', 'Population municipale', '')
('Sexe : Ensemble', 'Sexe (%)', 'Masculin')
('Sexe : Ensemble', 'Sexe (%)', 'Féminin')
('Sexe : Ensemble', 'Âge quinquennal (%)', '0-4 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '5-9 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '10-14 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '15-19 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '20-24 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '25-29 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '30-34 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '35-39 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '40-44 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '45-49 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '50-54 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '55-59 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '60-64 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '65-69 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '70-74 ans')
('Sexe : Ensemble', 'Âge quinquennal (%)', '75 ans ou plus')
('Sexe : Ensemble', 'Population de 15 ans et plus', '')
('Sexe : Ensemble', 'État matrimonial des 15 ans et plus (%)', 'Célibataire')
('Sexe : Ensemble', 'État matrimonial des 15 ans et plus (%)', 'Marié.e')
('Sexe : Ensemble', 'État matrimonial des 15 ans et plus (%)', 'Divorcé.e')
('Sexe : Ensemble', 'État matrimonial des 15 ans et plus (%)', 'Veuf.ve')
('Sexe : Ensemble', 'Âge moyen singulier au mariage', '')
('Sexe : Ensemble', 'Indicateur conjoncturel de fécondité', '')
('Sexe : Ensemble', 'Descendance finale des femmes', '')
('Sexe : Ensemble', 'Taux de prévalence du handicap (%)', '')
('Sexe : Ensemble', 'Population de 7-12 ans', '')
('Sexe : Ensemble', 'Taux de scolarisation des 6-11 ans en\xa02023/2024 (%)', '')
('Sexe : Ensemble', 'Population de 10 ans et plus', '')
('Sexe : Ensemble', "Taux d'analphabétisme des 10 ans et plus (%)", '')
('Sexe : Ensemble', 'Population de 15 ans et plus', '')
('Sexe : Ensemble', "Taux d'analphabétisme des 15 ans et plus (%)", '')
('Sexe : Ensemble', 'Population alphabète de 10 ans et plus', '')
('Sexe : Ensemble', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Arabe')
('Sexe : Ensemble', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Amazigh (Tifinagh)')
('Sexe : Ensemble', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Anglais')
('Sexe : Ensemble', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Français')
('Sexe : Ensemble', "Niveau d'études dans l'enseignement général (%)", "Aucun niveau d'études")
('Sexe : Ensemble', "Niveau d'études dans l'enseignement général (%)", 'Préscolaire')
('Sexe : Ensemble', "Niveau d'études dans l'enseignement général (%)", 'Primaire')
('Sexe : Ensemble', "Niveau d'études dans l'enseignement général (%)", 'Secondaire collégial')
('Sexe : Ensemble', "Niveau d'études dans l'enseignement général (%)", 'Secondaire qualifiant')
('Sexe : Ensemble', "Niveau d'études dans l'enseignement général (%)", 'Supérieur')
('Sexe : Ensemble', 'Langues locales utilisées (non exclusives) (%)', 'Darija')
('Sexe : Ensemble', 'Langues locales utilisées (non exclusives) (%)', 'Tachelhit')
('Sexe : Ensemble', 'Langues locales utilisées (non exclusives) (%)', 'Tamazight')
('Sexe : Ensemble', 'Langues locales utilisées (non exclusives) (%)', 'Tarifit')
('Sexe : Ensemble', 'Langues locales utilisées (non exclusives) (%)', 'Hassania')
('Sexe : Ensemble', 'Population de 15 ans et plus', '')
('Sexe : Ensemble', 'Population active de 15 ans et plus', '')
('Sexe : Ensemble', 'Population inactive de 15 ans et plus', '')
('Sexe : Ensemble', "Taux d'activité des 15 ans et plus (%)", '')
('Sexe : Ensemble', 'Taux de chômage (%)', '')
('Sexe : Ensemble', 'Population active occupée de 15 ans et plus', '')
('Sexe : Ensemble', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Employeur')
('Sexe : Ensemble', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Indépendant')
('Sexe : Ensemble', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Salarié du secteur public')
('Sexe : Ensemble', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Salarié du secteur privé')
('Sexe : Ensemble', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Aide familial')
('Sexe : Ensemble', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Apprenti')
('Sexe : Ensemble', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Coopérateur/Associé')
('Sexe : Ensemble', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Autre')
('Sexe : Ensemble', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Autre.1')
('Sexe : Masculin', 'Population municipale', '')
('Sexe : Masculin', 'Âge quinquennal (%)', '0-4 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '5-9 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '10-14 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '15-19 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '20-24 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '25-29 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '30-34 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '35-39 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '40-44 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '45-49 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '50-54 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '55-59 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '60-64 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '65-69 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '70-74 ans')
('Sexe : Masculin', 'Âge quinquennal (%)', '75 ans ou plus')
('Sexe : Masculin', 'Population de 15 ans et plus', '')
('Sexe : Masculin', 'État matrimonial des 15 ans et plus (%)', 'Célibataire')
('Sexe : Masculin', 'État matrimonial des 15 ans et plus (%)', 'Marié.e')
('Sexe : Masculin', 'État matrimonial des 15 ans et plus (%)', 'Divorcé.e')
('Sexe : Masculin', 'État matrimonial des 15 ans et plus (%)', 'Veuf.ve')
('Sexe : Masculin', 'Âge moyen singulier au mariage', '')
('Sexe : Masculin', 'Taux de prévalence du handicap (%)', '')
('Sexe : Masculin', 'Population de 7-12 ans', '')
('Sexe : Masculin', 'Taux de scolarisation des 6-11 ans en\xa02023/2024 (%)', '')
('Sexe : Masculin', 'Population de 10 ans et plus', '')
('Sexe : Masculin', "Taux d'analphabétisme des 10 ans et plus (%)", '')
('Sexe : Masculin', 'Population de 15 ans et plus', '')
('Sexe : Masculin', "Taux d'analphabétisme des 15 ans et plus (%)", '')
('Sexe : Masculin', 'Population alphabète de 10 ans et plus', '')
('Sexe : Masculin', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Arabe')
('Sexe : Masculin', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Amazigh (Tifinagh)')
('Sexe : Masculin', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Anglais')
('Sexe : Masculin', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Français')
('Sexe : Masculin', "Niveau d'études dans l'enseignement général (%)", "Aucun niveau d'études")
('Sexe : Masculin', "Niveau d'études dans l'enseignement général (%)", 'Préscolaire')
('Sexe : Masculin', "Niveau d'études dans l'enseignement général (%)", 'Primaire')
('Sexe : Masculin', "Niveau d'études dans l'enseignement général (%)", 'Secondaire collégial')
('Sexe : Masculin', "Niveau d'études dans l'enseignement général (%)", 'Secondaire qualifiant')
('Sexe : Masculin', "Niveau d'études dans l'enseignement général (%)", 'Supérieur')
('Sexe : Masculin', 'Langues locales utilisées (non exclusives) (%)', 'Darija')
('Sexe : Masculin', 'Langues locales utilisées (non exclusives) (%)', 'Tachelhit')
('Sexe : Masculin', 'Langues locales utilisées (non exclusives) (%)', 'Tamazight')
('Sexe : Masculin', 'Langues locales utilisées (non exclusives) (%)', 'Tarifit')
('Sexe : Masculin', 'Langues locales utilisées (non exclusives) (%)', 'Hassania')
('Sexe : Masculin', 'Population de 15 ans et plus', '')
('Sexe : Masculin', 'Population active de 15 ans et plus', '')
('Sexe : Masculin', 'Population inactive de 15 ans et plus', '')
('Sexe : Masculin', "Taux d'activité des 15 ans et plus (%)", '')
('Sexe : Masculin', 'Taux de chômage (%)', '')
('Sexe : Masculin', 'Population active occupée de 15 ans et plus', '')
('Sexe : Masculin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Employeur')
('Sexe : Masculin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Indépendant')
('Sexe : Masculin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Salarié du secteur public')
('Sexe : Masculin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Salarié du secteur privé')
('Sexe : Masculin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Aide familial')
('Sexe : Masculin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Apprenti')
('Sexe : Masculin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Coopérateur/Associé')
('Sexe : Masculin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Autre')
('Sexe : Masculin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Autre.1')
('Sexe : Féminin', 'Population municipale', '')
('Sexe : Féminin', 'Âge quinquennal (%)', '0-4 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '5-9 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '10-14 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '15-19 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '20-24 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '25-29 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '30-34 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '35-39 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '40-44 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '45-49 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '50-54 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '55-59 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '60-64 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '65-69 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '70-74 ans')
('Sexe : Féminin', 'Âge quinquennal (%)', '75 ans ou plus')
('Sexe : Féminin', 'Population de 15 ans et plus', '')
('Sexe : Féminin', 'État matrimonial des 15 ans et plus (%)', 'Célibataire')
('Sexe : Féminin', 'État matrimonial des 15 ans et plus (%)', 'Marié.e')
('Sexe : Féminin', 'État matrimonial des 15 ans et plus (%)', 'Divorcé.e')
('Sexe : Féminin', 'État matrimonial des 15 ans et plus (%)', 'Veuf.ve')
('Sexe : Féminin', 'Âge moyen singulier au mariage', '')
('Sexe : Féminin', 'Indicateur conjoncturel de fécondité', '')
('Sexe : Féminin', 'Descendance finale des femmes', '')
('Sexe : Féminin', 'Taux de prévalence du handicap (%)', '')
('Sexe : Féminin', 'Population de 7-12 ans', '')
('Sexe : Féminin', 'Taux de scolarisation des 6-11 ans en\xa02023/2024 (%)', '')
('Sexe : Féminin', 'Population de 10 ans et plus', '')
('Sexe : Féminin', "Taux d'analphabétisme des 10 ans et plus (%)", '')
('Sexe : Féminin', 'Population de 15 ans et plus', '')
('Sexe : Féminin', "Taux d'analphabétisme des 15 ans et plus (%)", '')
('Sexe : Féminin', 'Population alphabète de 10 ans et plus', '')
('Sexe : Féminin', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Arabe')
('Sexe : Féminin', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Amazigh (Tifinagh)')
('Sexe : Féminin', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Anglais')
('Sexe : Féminin', 'Langues lues et écrites par les alphabètes de 10 ans et plus (non exclusives) (%)', 'Français')
('Sexe : Féminin', "Niveau d'études dans l'enseignement général (%)", "Aucun niveau d'études")
('Sexe : Féminin', "Niveau d'études dans l'enseignement général (%)", 'Préscolaire')
('Sexe : Féminin', "Niveau d'études dans l'enseignement général (%)", 'Primaire')
('Sexe : Féminin', "Niveau d'études dans l'enseignement général (%)", 'Secondaire collégial')
('Sexe : Féminin', "Niveau d'études dans l'enseignement général (%)", 'Secondaire qualifiant')
('Sexe : Féminin', "Niveau d'études dans l'enseignement général (%)", 'Supérieur')
('Sexe : Féminin', 'Langues locales utilisées (non exclusives) (%)', 'Darija')
('Sexe : Féminin', 'Langues locales utilisées (non exclusives) (%)', 'Tachelhit')
('Sexe : Féminin', 'Langues locales utilisées (non exclusives) (%)', 'Tamazight')
('Sexe : Féminin', 'Langues locales utilisées (non exclusives) (%)', 'Tarifit')
('Sexe : Féminin', 'Langues locales utilisées (non exclusives) (%)', 'Hassania')
('Sexe : Féminin', 'Population de 15 ans et plus', '')
('Sexe : Féminin', 'Population active de 15 ans et plus', '')
('Sexe : Féminin', 'Population inactive de 15 ans et plus', '')
('Sexe : Féminin', "Taux d'activité des 15 ans et plus (%)", '')
('Sexe : Féminin', 'Taux de chômage (%)', '')
('Sexe : Féminin', 'Population active occupée de 15 ans et plus', '')
('Sexe : Féminin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Employeur')
('Sexe : Féminin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Indépendant')
('Sexe : Féminin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Salarié du secteur public')
('Sexe : Féminin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Salarié du secteur privé')
('Sexe : Féminin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Aide familial')
('Sexe : Féminin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Apprenti')
('Sexe : Féminin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Coopérateur/Associé')
('Sexe : Féminin', 'Statut professionnel des actifs occupés de 15 ans et plus (%)', 'Autre')

In [ ]:
# Flatten columns (tuples → strings séparées par un _)
def flatten_columns(df, sep="_"):
    df.columns = [sep.join(filter(None, map(str, col))).strip() for col in df.columns]
    return df

population_totale = flatten_columns(population_totale)
population_urbaine = flatten_columns(population_urbaine)
population_rurale = flatten_columns(population_rurale)

In [ ]:
population_totale

,Milieu de résidence : Ensemble_Code géographique,Milieu de résidence : Ensemble_Collectivités territoriales,Sexe : Ensemble_Population légale,Sexe : Ensemble_Population municipale,Sexe : Ensemble_Sexe (%)_Masculin,Sexe : Ensemble_Sexe (%)_Féminin,Sexe : Ensemble_Âge quinquennal (%)_0-4 ans,Sexe : Ensemble_Âge quinquennal (%)_5-9 ans,Sexe : Ensemble_Âge quinquennal (%)_10-14 ans,Sexe : Ensemble_Âge quinquennal (%)_15-19 ans,...,Sexe : Féminin_Taux de chômage (%),Sexe : Féminin_Population active occupée de 15 ans et plus,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Employeur,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Indépendant,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur public,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur privé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Aide familial,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Apprenti,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Coopérateur/Associé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Autre
0,NaN,Ensemble du territoire national,36828330,36490591,49.9,50.1,7.6,9.3,9.6,8.2,...,25.9,1696785,1.7,11.2,21.7,58.8,2.8,0.4,0.9,2.4
1,1.0,Région de Tanger-Tétouan-Al Hoceima,4030222,4008655,50.8,49.2,8.2,9.6,9.4,7.9,...,23,232294,1.3,11.3,15.4,62.3,7,0.3,0.9,1.6
2,1511.0,Préfecture de Tanger-Assilah,1494413,1487236,50.8,49.2,8.5,9.4,8.8,7.4,...,17.8,127760,1.5,7.4,10.5,77.1,1.3,0.3,0.7,1.3
3,1511010.0,Commune de Tanger,1275428,1272718,50.6,49.4,8.3,9.2,8.6,7.4,...,17.7,114125,1.5,6.8,10.4,78.4,0.7,0.3,0.7,1.3
4,15110105.0,Arrondissement de Mghogha,252656,252177,50.8,49.2,8.2,9.3,9,7.6,...,20,21357,1.4,6.5,7.7,81.2,0.7,0.2,0.7,1.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,1206603.0,Cercle d'Aousserd,12188,2010,56,44,9.4,10,8.8,6.9,...,21.8,97,1,9.3,17.5,62.9,6.2,0,0,3.1
2013,120660305.0,Commune d'Aousserd,3855,273,76.2,23.8,3.3,2.6,6.2,2.6,...,10,9,0,11.1,22.2,0,55.6,0,0,11.1
2014,120660303.0,Commune d'Aghouinite*,1006,1006,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
2015,120660309.0,Commune de Zoug*,592,592,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
2016,120660307.0,Commune de Tichla,6735,139,57.6,42.4,17.3,12.2,7.9,6.5,...,50,1,0,0,100,0,0,0,0,0

In [ ]:
population_totale

,Milieu de résidence : Ensemble_Code géographique,Milieu de résidence : Ensemble_Collectivités territoriales,Sexe : Ensemble_Population légale,Sexe : Ensemble_Population municipale,Sexe : Ensemble_Sexe (%)_Masculin,Sexe : Ensemble_Sexe (%)_Féminin,Sexe : Ensemble_Âge quinquennal (%)_0-4 ans,Sexe : Ensemble_Âge quinquennal (%)_5-9 ans,Sexe : Ensemble_Âge quinquennal (%)_10-14 ans,Sexe : Ensemble_Âge quinquennal (%)_15-19 ans,...,Sexe : Féminin_Taux de chômage (%),Sexe : Féminin_Population active occupée de 15 ans et plus,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Employeur,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Indépendant,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur public,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur privé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Aide familial,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Apprenti,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Coopérateur/Associé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Autre
0,NaN,Ensemble du territoire national,36828330,36490591,49.9,50.1,7.6,9.3,9.6,8.2,...,25.9,1696785,1.7,11.2,21.7,58.8,2.8,0.4,0.9,2.4
1,1.0,Région de Tanger-Tétouan-Al Hoceima,4030222,4008655,50.8,49.2,8.2,9.6,9.4,7.9,...,23,232294,1.3,11.3,15.4,62.3,7,0.3,0.9,1.6
2,1511.0,Préfecture de Tanger-Assilah,1494413,1487236,50.8,49.2,8.5,9.4,8.8,7.4,...,17.8,127760,1.5,7.4,10.5,77.1,1.3,0.3,0.7,1.3
3,1511010.0,Commune de Tanger,1275428,1272718,50.6,49.4,8.3,9.2,8.6,7.4,...,17.7,114125,1.5,6.8,10.4,78.4,0.7,0.3,0.7,1.3
4,15110105.0,Arrondissement de Mghogha,252656,252177,50.8,49.2,8.2,9.3,9,7.6,...,20,21357,1.4,6.5,7.7,81.2,0.7,0.2,0.7,1.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,1206603.0,Cercle d'Aousserd,12188,2010,56,44,9.4,10,8.8,6.9,...,21.8,97,1,9.3,17.5,62.9,6.2,0,0,3.1
2013,120660305.0,Commune d'Aousserd,3855,273,76.2,23.8,3.3,2.6,6.2,2.6,...,10,9,0,11.1,22.2,0,55.6,0,0,11.1
2014,120660303.0,Commune d'Aghouinite*,1006,1006,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
2015,120660309.0,Commune de Zoug*,592,592,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
2016,120660307.0,Commune de Tichla,6735,139,57.6,42.4,17.3,12.2,7.9,6.5,...,50,1,0,0,100,0,0,0,0,0

In [ ]:
#Ménages sheets with 2 header rows
menages = pd.read_excel(RGPH2024, sheet_name="Ménages", header=[0,1])
menages_urbains = pd.read_excel(RGPH2024, sheet_name="Ménages_Urbains", header=[0,1])
menages_ruraux = pd.read_excel(RGPH2024, sheet_name="Ménages_Ruraux", header=[0,1])

# Clean and forward-fill headers
menages = clean_multilevel_columns(menages)
menages = forward_fill_column_levels(menages)

menages_urbains = clean_multilevel_columns(menages_urbains)
menages_urbains = forward_fill_column_levels(menages_urbains)

menages_ruraux = clean_multilevel_columns(menages_ruraux)
menages_ruraux = forward_fill_column_levels(menages_ruraux)

# Check columns of menages
for col in menages.columns:
    print(col)

('Milieu de résidence : Ensemble', 'Code géographique')
('Milieu de résidence : Ensemble', 'Collectivités territoriales')
('Population municipale', 'Pop_municipale')
('Ménages', 'Ménages population')
('Taille moyenne des ménages', 'Taille moyenne')
('Ménages sédentaires', '')
('Type de logement (%)', 'Villa / Étage\xa0de villa')
('Type de logement (%)', 'Appartement')
('Type de logement (%)', 'Maison marocaine')
('Type de logement (%)', 'Maison sommaire / Bidonville')
('Type de logement (%)', 'Logement rural')
('Type de logement (%)', 'Autre')
("Nombre moyen de personnes par pièce d'habitation", '')
("Statut d'occupation du logement (%)", 'Propriétaire')
("Statut d'occupation du logement (%)", 'Locataire')
("Statut d'occupation du logement (%)", 'Autre')
('Âge du logement (%)', 'Moins de 10 ans')
('Âge du logement (%)', '10-19 ans')
('Âge du logement (%)', '20-49 ans')
('Âge du logement (%)', '50 ans ou plus')
('Disponibilité des éléments essentiels de confort (%)', 'Cuisine')
('Disponibilité des éléments essentiels de confort (%)', 'W.-C.')
('Disponibilité des éléments essentiels de confort (%)', "Pièce d'eau")
('Disponibilité des éléments essentiels de confort (%)', 'Électricité')
('Disponibilité des éléments essentiels de confort (%)', 'Eau courante')
('Mode d’évacuation des eaux usées (%)', "Réseau public d'assainissement")
('Mode d’évacuation des eaux usées (%)', 'Fosse septique')
('Mode d’évacuation des eaux usées (%)', 'Autre')
('Mode d’évacuation des déchets ménagers (%)', 'Bac à ordures de la commune')
('Mode d’évacuation des déchets ménagers (%)', 'Camion de la commune / Camion privé')
('Mode d’évacuation des déchets ménagers (%)', 'Dans la nature')
('Mode d’évacuation des déchets ménagers (%)', 'Autre')
('Combustible de cuisson utilisé (%)', 'Gaz')
('Combustible de cuisson utilisé (%)', 'Électricité')
('Combustible de cuisson utilisé (%)', 'Charbon')
('Combustible de cuisson utilisé (%)', 'Bois énergie')
('Combustible de cuisson utilisé (%)', 'Autre')
('Distance moyenne des logements à la route goudronnée (Km)', '')

In [ ]:
population_totale.columns

Index(['Milieu de résidence : Ensemble_Code géographique',
       'Milieu de résidence : Ensemble_Collectivités territoriales',
       'Sexe : Ensemble_Population légale',
       'Sexe : Ensemble_Population municipale',
       'Sexe : Ensemble_Sexe (%)_Masculin', 'Sexe : Ensemble_Sexe (%)_Féminin',
       'Sexe : Ensemble_Âge quinquennal (%)_0-4 ans',
       'Sexe : Ensemble_Âge quinquennal (%)_5-9 ans',
       'Sexe : Ensemble_Âge quinquennal (%)_10-14 ans',
       'Sexe : Ensemble_Âge quinquennal (%)_15-19 ans',
       ...
       'Sexe : Féminin_Taux de chômage (%)',
       'Sexe : Féminin_Population active occupée de 15 ans et plus',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Employeur',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Indépendant',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur public',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur privé',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Aide familial',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Apprenti',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Coopérateur/Associé',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Autre'],
      dtype='object', length=191)

In [ ]:
population_urbaine.columns

Index(['Milieu de résidence : Urbain_Code géographique',
       'Milieu de résidence : Urbain_Collectivités territoriales',
       'Sexe : Ensemble_Population légale',
       'Sexe : Ensemble_Population municipale',
       'Sexe : Ensemble_Sexe (%)_Masculin', 'Sexe : Ensemble_Sexe (%)_Féminin',
       'Sexe : Ensemble_Âge quinquennal (%)_0-4 ans',
       'Sexe : Ensemble_Âge quinquennal (%)_5-9 ans',
       'Sexe : Ensemble_Âge quinquennal (%)_10-14 ans',
       'Sexe : Ensemble_Âge quinquennal (%)_15-19 ans',
       ...
       'Sexe : Féminin_Taux de chômage (%)',
       'Sexe : Féminin_Population active occupée de 15 ans et plus',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Employeur',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Indépendant',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur public',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur privé',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Aide familial',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Apprenti',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Coopérateur/Associé',
       'Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Autre'],
      dtype='object', length=191)

In [ ]:
# Aplatir les colonnes à 2 niveaux (utile pour manipulation et visualisation)
menages = flatten_columns(menages)
menages_urbains = flatten_columns(menages_urbains)
menages_ruraux = flatten_columns(menages_ruraux)

In [ ]:
menages

,Milieu de résidence : Ensemble_Code géographique,Milieu de résidence : Ensemble_Collectivités territoriales,Population municipale_Pop_municipale,Ménages_Ménages population,Taille moyenne des ménages_Taille moyenne,Ménages sédentaires,Type de logement (%)_Villa / Étage de villa,Type de logement (%)_Appartement,Type de logement (%)_Maison marocaine,Type de logement (%)_Maison sommaire / Bidonville,...,Mode d’évacuation des déchets ménagers (%)_Bac à ordures de la commune,Mode d’évacuation des déchets ménagers (%)_Camion de la commune / Camion privé,Mode d’évacuation des déchets ménagers (%)_Dans la nature,Mode d’évacuation des déchets ménagers (%)_Autre,Combustible de cuisson utilisé (%)_Gaz,Combustible de cuisson utilisé (%)_Électricité,Combustible de cuisson utilisé (%)_Charbon,Combustible de cuisson utilisé (%)_Bois énergie,Combustible de cuisson utilisé (%)_Autre,Distance moyenne des logements à la route goudronnée (Km)
0,NaN,Ensemble du territoire national,36490591,9275038,3.9,9263270,1.9,16.6,58.8,3,...,56.5,15,26.6,1.9,95.2,0.4,0.2,4,0.2,1.5
1,1.0,Région de Tanger-Tétouan-Al Hoceima,4008655,1048860,3.8,1047295,0.9,16.1,66.3,1,...,65.6,6.5,25.7,2.2,97.7,0.4,0.3,1.4,0.1,2.3
2,1511.0,Préfecture de Tanger-Assilah,1487236,418844,3.6,418108,1.4,25.1,70.2,0.7,...,86.7,9,3.4,0.9,99.3,0.5,0,0.1,0.1,0.8
3,1511010.0,Commune de Tanger,1272718,362062,3.5,361404,1.5,25.6,71.7,0.4,...,90.1,9.2,0.3,0.4,99.3,0.6,0,0,0.1,…
4,15110105.0,Arrondissement de Mghogha,252177,70679,3.6,70596,2,14.9,82.1,0.3,...,81.8,17.2,0.7,0.4,99.4,0.4,0,0,0.1,…
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,1206603.0,Cercle d'Aousserd,2010,565,3.6,502,0,8.2,18.5,55,...,23.9,0,74.5,1.6,100,0,0,0,0,4.8
2013,120660305.0,Commune d'Aousserd,273,106,2.6,51,0,27.5,54.9,3.9,...,84.3,0,13.7,2,100,0,0,0,0,1.1
2014,120660303.0,Commune d'Aghouinite*,1006,263,3.8,263,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
2015,120660309.0,Commune de Zoug*,592,155,3.8,155,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
2016,120660307.0,Commune de Tichla,139,41,3.4,33,0,0,42.4,3,...,0,0,100,0,100,0,0,0,0,45

In [ ]:
# Check population sheets columns
print(set(population_totale.columns) == set(population_urbaine.columns) == set(population_rurale.columns))  # Should return True

# Check menages sheets columns
print(set(menages.columns) == set(menages_urbains.columns) == set(menages_ruraux.columns))  # Should return True

False
False

In [ ]:
#confirmer if the pb only on two first cols
pop_cols1 = set(population_totale.columns[2:])
pop_cols2 = set(population_urbaine.columns[2:])
pop_cols3 = set(population_rurale.columns[2:])

print(pop_cols1 == pop_cols2 == pop_cols3)

True

In [ ]:
# Rename first two columns for clarity
population_totale.rename(columns={population_totale.columns[0]: "Code_geographique",
                                 population_totale.columns[1]: "Collectivites_territoriales"}, inplace=True)
population_urbaine.rename(columns={population_urbaine.columns[0]: "Code_geographique",
                                  population_urbaine.columns[1]: "Collectivites_territoriales"}, inplace=True)
population_rurale.rename(columns={population_rurale.columns[0]: "Code_geographique",
                                 population_rurale.columns[1]: "Collectivites_territoriales"}, inplace=True)

# Add the Milieu column
population_totale['Milieu'] = 'Ensemble'
population_urbaine['Milieu'] = 'Urbain'
population_rurale['Milieu'] = 'Rural'

In [ ]:
# Check population sheets columns
print(set(population_totale.columns) == set(population_urbaine.columns) == set(population_rurale.columns))  # Should return True

True

In [ ]:
# Concatenate all population data
population_all = pd.concat([population_totale, population_urbaine, population_rurale], ignore_index=True)

In [ ]:
population_all

,Code_geographique,Collectivites_territoriales,Sexe : Ensemble_Population légale,Sexe : Ensemble_Population municipale,Sexe : Ensemble_Sexe (%)_Masculin,Sexe : Ensemble_Sexe (%)_Féminin,Sexe : Ensemble_Âge quinquennal (%)_0-4 ans,Sexe : Ensemble_Âge quinquennal (%)_5-9 ans,Sexe : Ensemble_Âge quinquennal (%)_10-14 ans,Sexe : Ensemble_Âge quinquennal (%)_15-19 ans,...,Sexe : Féminin_Population active occupée de 15 ans et plus,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Employeur,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Indépendant,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur public,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur privé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Aide familial,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Apprenti,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Coopérateur/Associé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Autre,Milieu
0,NaN,Ensemble du territoire national,36828330,36490591,49.9,50.1,7.6,9.3,9.6,8.2,...,1696785,1.7,11.2,21.7,58.8,2.8,0.4,0.9,2.4,Ensemble
1,1.0,Région de Tanger-Tétouan-Al Hoceima,4030222,4008655,50.8,49.2,8.2,9.6,9.4,7.9,...,232294,1.3,11.3,15.4,62.3,7,0.3,0.9,1.6,Ensemble
2,1511.0,Préfecture de Tanger-Assilah,1494413,1487236,50.8,49.2,8.5,9.4,8.8,7.4,...,127760,1.5,7.4,10.5,77.1,1.3,0.3,0.7,1.3,Ensemble
3,1511010.0,Commune de Tanger,1275428,1272718,50.6,49.4,8.3,9.2,8.6,7.4,...,114125,1.5,6.8,10.4,78.4,0.7,0.3,0.7,1.3,Ensemble
4,15110105.0,Arrondissement de Mghogha,252656,252177,50.8,49.2,8.2,9.3,9,7.6,...,21357,1.4,6.5,7.7,81.2,0.7,0.2,0.7,1.6,Ensemble
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6046,1206603.0,Cercle d'Aousserd,12188,2010,56,44,9.4,10,8.8,6.9,...,97,1,9.3,17.5,62.9,6.2,0,0,3.1,Rural
6047,120660305.0,Commune d'Aousserd,3855,273,76.2,23.8,3.3,2.6,6.2,2.6,...,9,0,11.1,22.2,0,55.6,0,0,11.1,Rural
6048,120660303.0,Commune d'Aghouinite*,1006,1006,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,Rural
6049,120660309.0,Commune de Zoug*,592,592,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,Rural
6050,120660307.0,Commune de Tichla,6735,139,57.6,42.4,17.3,12.2,7.9,6.5,...,1,0,0,100,0,0,0,0,0,Rural

In [ ]:
#confirmer if the pb only on two first cols
menage_cols1 = set(menages.columns[2:])
menage_cols2 = set(menages_urbains.columns[2:])
menage_cols3 = set(menages_ruraux.columns[2:])

print(menage_cols1 == menage_cols2 == menage_cols3)

False

In [ ]:
menages_ruraux.columns

Index(['Milieu de résidence : Rural_Code géographique',
       'Milieu de résidence : Rural_Collectivités territoriales',
       'Population municipale_Ménages population', 'Ménages',
       'Taille moyenne des ménages_Taille moyenne',
       'Ménages sédentaires_Pop_municipale',
       'Type de logement (%)_Villa / Étage de villa',
       'Type de logement (%)_Appartement',
       'Type de logement (%)_Maison marocaine',
       'Type de logement (%)_Maison sommaire / Bidonville',
       'Type de logement (%)_Logement rural', 'Type de logement (%)_Autre',
       'Nombre moyen de personnes par pièce d'habitation',
       'Statut d'occupation du logement (%)_Propriétaire',
       'Statut d'occupation du logement (%)_Locataire',
       'Statut d'occupation du logement (%)_Autre',
       'Âge du logement (%)_Moins de 10 ans', 'Âge du logement (%)_10-19 ans',
       'Âge du logement (%)_20-49 ans', 'Âge du logement (%)_50 ans ou plus',
       'Disponibilité des éléments essentiels de confort (%)_Cuisine',
       'Disponibilité des éléments essentiels de confort (%)_W.-C.',
       'Disponibilité des éléments essentiels de confort (%)_Pièce d'eau',
       'Disponibilité des éléments essentiels de confort (%)_Électricité',
       'Disponibilité des éléments essentiels de confort (%)_Eau courante',
       'Mode d’évacuation des eaux usées (%)_Réseau public d'assainissement',
       'Mode d’évacuation des eaux usées (%)_Fosse septique',
       'Mode d’évacuation des eaux usées (%)_Autre',
       'Mode d’évacuation des déchets ménagers (%)_Bac à ordures de la commune',
       'Mode d’évacuation des déchets ménagers (%)_Camion de la commune / Camion privé',
       'Mode d’évacuation des déchets ménagers (%)_Dans la nature',
       'Mode d’évacuation des déchets ménagers (%)_Autre',
       'Combustible de cuisson utilisé (%)_Gaz',
       'Combustible de cuisson utilisé (%)_Électricité',
       'Combustible de cuisson utilisé (%)_Charbon',
       'Combustible de cuisson utilisé (%)_Bois énergie',
       'Combustible de cuisson utilisé (%)_Autre',
       'Distance moyenne des logements à la route goudronnée (Km)'],
      dtype='object')

In [ ]:
menages_urbains.columns

Index(['Milieu de résidence : Urbain_Code géographique',
       'Milieu de résidence : Urbain_Collectivités territoriales',
       'Population municipale_Pop_municipale', 'Ménages_Ménages population',
       'Taille moyenne des ménages_Taille moyenne', 'Ménages sédentaires',
       'Type de logement (%)_Villa / Étage de villa',
       'Type de logement (%)_Appartement',
       'Type de logement (%)_Maison marocaine',
       'Type de logement (%)_Maison sommaire / Bidonville',
       'Type de logement (%)_Logement rural', 'Type de logement (%)_Autre',
       'Nombre moyen de personnes par pièce d'habitation',
       'Statut d'occupation du logement (%)_Propriétaire',
       'Statut d'occupation du logement (%)_Locataire',
       'Statut d'occupation du logement (%)_Autre',
       'Âge du logement (%)_Moins de 10 ans', 'Âge du logement (%)_10-19 ans',
       'Âge du logement (%)_20-49 ans', 'Âge du logement (%)_50 ans ou plus',
       'Disponibilité des éléments essentiels de confort (%)_Cuisine',
       'Disponibilité des éléments essentiels de confort (%)_W.-C.',
       'Disponibilité des éléments essentiels de confort (%)_Pièce d'eau',
       'Disponibilité des éléments essentiels de confort (%)_Électricité',
       'Disponibilité des éléments essentiels de confort (%)_Eau courante',
       'Mode d’évacuation des eaux usées (%)_Réseau public d'assainissement',
       'Mode d’évacuation des eaux usées (%)_Fosse septique',
       'Mode d’évacuation des eaux usées (%)_Autre',
       'Mode d’évacuation des déchets ménagers (%)_Bac à ordures de la commune',
       'Mode d’évacuation des déchets ménagers (%)_Camion de la commune / Camion privé',
       'Mode d’évacuation des déchets ménagers (%)_Dans la nature',
       'Mode d’évacuation des déchets ménagers (%)_Autre',
       'Combustible de cuisson utilisé (%)_Gaz',
       'Combustible de cuisson utilisé (%)_Électricité',
       'Combustible de cuisson utilisé (%)_Charbon',
       'Combustible de cuisson utilisé (%)_Bois énergie',
       'Combustible de cuisson utilisé (%)_Autre',
       'Distance moyenne des logements à la route goudronnée (Km)'],
      dtype='object')

In [ ]:
menages.columns

Index(['Milieu de résidence : Ensemble_Code géographique',
       'Milieu de résidence : Ensemble_Collectivités territoriales',
       'Population municipale_Pop_municipale', 'Ménages_Ménages population',
       'Taille moyenne des ménages_Taille moyenne', 'Ménages sédentaires',
       'Type de logement (%)_Villa / Étage de villa',
       'Type de logement (%)_Appartement',
       'Type de logement (%)_Maison marocaine',
       'Type de logement (%)_Maison sommaire / Bidonville',
       'Type de logement (%)_Logement rural', 'Type de logement (%)_Autre',
       'Nombre moyen de personnes par pièce d'habitation',
       'Statut d'occupation du logement (%)_Propriétaire',
       'Statut d'occupation du logement (%)_Locataire',
       'Statut d'occupation du logement (%)_Autre',
       'Âge du logement (%)_Moins de 10 ans', 'Âge du logement (%)_10-19 ans',
       'Âge du logement (%)_20-49 ans', 'Âge du logement (%)_50 ans ou plus',
       'Disponibilité des éléments essentiels de confort (%)_Cuisine',
       'Disponibilité des éléments essentiels de confort (%)_W.-C.',
       'Disponibilité des éléments essentiels de confort (%)_Pièce d'eau',
       'Disponibilité des éléments essentiels de confort (%)_Électricité',
       'Disponibilité des éléments essentiels de confort (%)_Eau courante',
       'Mode d’évacuation des eaux usées (%)_Réseau public d'assainissement',
       'Mode d’évacuation des eaux usées (%)_Fosse septique',
       'Mode d’évacuation des eaux usées (%)_Autre',
       'Mode d’évacuation des déchets ménagers (%)_Bac à ordures de la commune',
       'Mode d’évacuation des déchets ménagers (%)_Camion de la commune / Camion privé',
       'Mode d’évacuation des déchets ménagers (%)_Dans la nature',
       'Mode d’évacuation des déchets ménagers (%)_Autre',
       'Combustible de cuisson utilisé (%)_Gaz',
       'Combustible de cuisson utilisé (%)_Électricité',
       'Combustible de cuisson utilisé (%)_Charbon',
       'Combustible de cuisson utilisé (%)_Bois énergie',
       'Combustible de cuisson utilisé (%)_Autre',
       'Distance moyenne des logements à la route goudronnée (Km)'],
      dtype='object')

In [ ]:
# Rename columns for menages
menages.rename(columns={menages.columns[0]: "Code_geographique",
                       menages.columns[1]: "Collectivites_territoriales"}, inplace=True)
menages_urbains.rename(columns={menages_urbains.columns[0]: "Code_geographique",
                               menages_urbains.columns[1]: "Collectivites_territoriales"}, inplace=True)
menages_ruraux.rename(columns={menages_ruraux.columns[0]: "Code_geographique",
                              menages_ruraux.columns[1]: "Collectivites_territoriales"}, inplace=True)

# Add Milieu column
menages['Milieu'] = 'Ensemble'
menages_urbains['Milieu'] = 'Urbain'
menages_ruraux['Milieu'] = 'Rural'

In [ ]:
# Check menages sheets columns
print(set(menages.columns) == set(menages_urbains.columns) == set(menages_ruraux.columns))  # Should return True

False

In [ ]:
# Find the difference in columns between menages and menages_urbains (excluding the first two columns)
diff1 = set(menages.columns[2:]) - set(menages_urbains.columns[2:])
print("Columns in menages but not in menages_urbains:", diff1)

# Find the difference in columns between menages_urbains and menages (excluding the first two columns)
diff2 = set(menages_urbains.columns[2:]) - set(menages.columns[2:])
print("Columns in menages_urbains but not in menages:", diff2)

# Find the difference in columns between menages and menages_ruraux (excluding the first two columns)
diff3 = set(menages.columns[2:]) - set(menages_ruraux.columns[2:])
print("Columns in menages but not in menages_ruraux:", diff3)

# Find the difference in columns between menages_ruraux and menages (excluding the first two columns)
diff4 = set(menages_ruraux.columns[2:]) - set(menages.columns[2:])
print("Columns in menages_ruraux but not in menages:", diff4)

# Find the difference in columns between menages_urbains and menages_ruraux (excluding the first two columns)
diff5 = set(menages_urbains.columns[2:]) - set(menages_ruraux.columns[2:])
print("Columns in menages_urbains but not in menages_ruraux:", diff5)

# Find the difference in columns between menages_ruraux and menages_urbains (excluding the first two columns)
diff6 = set(menages_ruraux.columns[2:]) - set(menages_urbains.columns[2:])
print("Columns in menages_ruraux but not in menages_urbains:", diff6)

Columns in menages but not in menages_urbains: set()
Columns in menages_urbains but not in menages: set()
Columns in menages but not in menages_ruraux: {'Population municipale_Pop_municipale', 'Ménages_Ménages population', 'Ménages sédentaires'}
Columns in menages_ruraux but not in menages: {'Population municipale_Ménages population', 'Ménages sédentaires_Pop_municipale', 'Ménages'}
Columns in menages_urbains but not in menages_ruraux: {'Population municipale_Pop_municipale', 'Ménages_Ménages population', 'Ménages sédentaires'}
Columns in menages_ruraux but not in menages_urbains: {'Population municipale_Ménages population', 'Ménages sédentaires_Pop_municipale', 'Ménages'}

In [ ]:
# Affichage des colonnes problématiques
print("Colonnes menages :", menages.columns[2:].tolist())
print("Colonnes menages_ruraux :", menages_ruraux.columns[2:].tolist())

# Dictionnaire de renommage des colonnes de menages_ruraux pour correspondre à menages
rename_dict = {
    'Population municipale_Ménages population': 'Ménages_Ménages population',
    'Ménages sédentaires_Pop_municipale': 'Ménages sédentaires',
    'Ménages': 'Population municipale_Pop_municipale'
}

menages_ruraux.rename(columns=rename_dict, inplace=True)

# Ajouter les colonnes manquantes à menages_ruraux, si besoin, avec des NaN
for col in menages.columns[2:]:
    if col not in menages_ruraux.columns:
        menages_ruraux[col] = pd.NA

# Réordonner les colonnes de menages_ruraux pour correspondre à menages
menages_ruraux = menages_ruraux[menages.columns]

# Vérifier que c’est ok
print(menages_ruraux.columns.tolist())

Colonnes menages : ['Population municipale_Pop_municipale', 'Ménages_Ménages population', 'Taille moyenne des ménages_Taille moyenne', 'Ménages sédentaires', 'Type de logement (%)_Villa / Étage\xa0de villa', 'Type de logement (%)_Appartement', 'Type de logement (%)_Maison marocaine', 'Type de logement (%)_Maison sommaire / Bidonville', 'Type de logement (%)_Logement rural', 'Type de logement (%)_Autre', "Nombre moyen de personnes par pièce d'habitation", "Statut d'occupation du logement (%)_Propriétaire", "Statut d'occupation du logement (%)_Locataire", "Statut d'occupation du logement (%)_Autre", 'Âge du logement (%)_Moins de 10 ans', 'Âge du logement (%)_10-19 ans', 'Âge du logement (%)_20-49 ans', 'Âge du logement (%)_50 ans ou plus', 'Disponibilité des éléments essentiels de confort (%)_Cuisine', 'Disponibilité des éléments essentiels de confort (%)_W.-C.', "Disponibilité des éléments essentiels de confort (%)_Pièce d'eau", 'Disponibilité des éléments essentiels de confort (%)_Électricité', 'Disponibilité des éléments essentiels de confort (%)_Eau courante', "Mode d’évacuation des eaux usées (%)_Réseau public d'assainissement", 'Mode d’évacuation des eaux usées (%)_Fosse septique', 'Mode d’évacuation des eaux usées (%)_Autre', 'Mode d’évacuation des déchets ménagers (%)_Bac à ordures de la commune', 'Mode d’évacuation des déchets ménagers (%)_Camion de la commune / Camion privé', 'Mode d’évacuation des déchets ménagers (%)_Dans la nature', 'Mode d’évacuation des déchets ménagers (%)_Autre', 'Combustible de cuisson utilisé (%)_Gaz', 'Combustible de cuisson utilisé (%)_Électricité', 'Combustible de cuisson utilisé (%)_Charbon', 'Combustible de cuisson utilisé (%)_Bois énergie', 'Combustible de cuisson utilisé (%)_Autre', 'Distance moyenne des logements à la route goudronnée (Km)', 'Milieu']
Colonnes menages_ruraux : ['Population municipale_Ménages population', 'Ménages', 'Taille moyenne des ménages_Taille moyenne', 'Ménages sédentaires_Pop_municipale', 'Type de logement (%)_Villa / Étage\xa0de villa', 'Type de logement (%)_Appartement', 'Type de logement (%)_Maison marocaine', 'Type de logement (%)_Maison sommaire / Bidonville', 'Type de logement (%)_Logement rural', 'Type de logement (%)_Autre', "Nombre moyen de personnes par pièce d'habitation", "Statut d'occupation du logement (%)_Propriétaire", "Statut d'occupation du logement (%)_Locataire", "Statut d'occupation du logement (%)_Autre", 'Âge du logement (%)_Moins de 10 ans', 'Âge du logement (%)_10-19 ans', 'Âge du logement (%)_20-49 ans', 'Âge du logement (%)_50 ans ou plus', 'Disponibilité des éléments essentiels de confort (%)_Cuisine', 'Disponibilité des éléments essentiels de confort (%)_W.-C.', "Disponibilité des éléments essentiels de confort (%)_Pièce d'eau", 'Disponibilité des éléments essentiels de confort (%)_Électricité', 'Disponibilité des éléments essentiels de confort (%)_Eau courante', "Mode d’évacuation des eaux usées (%)_Réseau public d'assainissement", 'Mode d’évacuation des eaux usées (%)_Fosse septique', 'Mode d’évacuation des eaux usées (%)_Autre', 'Mode d’évacuation des déchets ménagers (%)_Bac à ordures de la commune', 'Mode d’évacuation des déchets ménagers (%)_Camion de la commune / Camion privé', 'Mode d’évacuation des déchets ménagers (%)_Dans la nature', 'Mode d’évacuation des déchets ménagers (%)_Autre', 'Combustible de cuisson utilisé (%)_Gaz', 'Combustible de cuisson utilisé (%)_Électricité', 'Combustible de cuisson utilisé (%)_Charbon', 'Combustible de cuisson utilisé (%)_Bois énergie', 'Combustible de cuisson utilisé (%)_Autre', 'Distance moyenne des logements à la route goudronnée (Km)', 'Milieu']
['Code_geographique', 'Collectivites_territoriales', 'Population municipale_Pop_municipale', 'Ménages_Ménages population', 'Taille moyenne des ménages_Taille moyenne', 'Ménages sédentaires', 'Type de logement (%)_Villa / Étage\xa0de villa', 'Type de logement (%)_Appartement', 'Type de logement (%)_Maison marocaine', 'Type de logement (%)_Maison sommaire / Bidonville', 'Type de logement (%)_Logement rural', 'Type de logement (%)_Autre', "Nombre moyen de personnes par pièce d'habitation", "Statut d'occupation du logement (%)_Propriétaire", "Statut d'occupation du logement (%)_Locataire", "Statut d'occupation du logement (%)_Autre", 'Âge du logement (%)_Moins de 10 ans', 'Âge du logement (%)_10-19 ans', 'Âge du logement (%)_20-49 ans', 'Âge du logement (%)_50 ans ou plus', 'Disponibilité des éléments essentiels de confort (%)_Cuisine', 'Disponibilité des éléments essentiels de confort (%)_W.-C.', "Disponibilité des éléments essentiels de confort (%)_Pièce d'eau", 'Disponibilité des éléments essentiels de confort (%)_Électricité', 'Disponibilité des éléments essentiels de confort (%)_Eau courante', "Mode d’évacuation des eaux usées (%)_Réseau public d'assainissement", 'Mode d’évacuation des eaux usées (%)_Fosse septique', 'Mode d’évacuation des eaux usées (%)_Autre', 'Mode d’évacuation des déchets ménagers (%)_Bac à ordures de la commune', 'Mode d’évacuation des déchets ménagers (%)_Camion de la commune / Camion privé', 'Mode d’évacuation des déchets ménagers (%)_Dans la nature', 'Mode d’évacuation des déchets ménagers (%)_Autre', 'Combustible de cuisson utilisé (%)_Gaz', 'Combustible de cuisson utilisé (%)_Électricité', 'Combustible de cuisson utilisé (%)_Charbon', 'Combustible de cuisson utilisé (%)_Bois énergie', 'Combustible de cuisson utilisé (%)_Autre', 'Distance moyenne des logements à la route goudronnée (Km)', 'Milieu']

In [ ]:
# For population sheets, skip first 2 columns (milieu and code géographique)
menage_cols1 = set(menages.columns[2:])
menage_cols2 = set(menages_urbains.columns[2:])
menage_cols3 = set(menages_ruraux.columns[2:])

print(menage_cols1 == menage_cols2 == menage_cols3)  # Should be True if data columns match

True

In [ ]:
# Concaténation finale des ménages
menages_all = pd.concat([menages, menages_urbains, menages_ruraux], ignore_index=True)

# Vérifier les premières lignes
menages_all

,Code_geographique,Collectivites_territoriales,Population municipale_Pop_municipale,Ménages_Ménages population,Taille moyenne des ménages_Taille moyenne,Ménages sédentaires,Type de logement (%)_Villa / Étage de villa,Type de logement (%)_Appartement,Type de logement (%)_Maison marocaine,Type de logement (%)_Maison sommaire / Bidonville,...,Mode d’évacuation des déchets ménagers (%)_Camion de la commune / Camion privé,Mode d’évacuation des déchets ménagers (%)_Dans la nature,Mode d’évacuation des déchets ménagers (%)_Autre,Combustible de cuisson utilisé (%)_Gaz,Combustible de cuisson utilisé (%)_Électricité,Combustible de cuisson utilisé (%)_Charbon,Combustible de cuisson utilisé (%)_Bois énergie,Combustible de cuisson utilisé (%)_Autre,Distance moyenne des logements à la route goudronnée (Km),Milieu
0,NaN,Ensemble du territoire national,36490591,9275038,3.9,9263270,1.9,16.6,58.8,3,...,15,26.6,1.9,95.2,0.4,0.2,4,0.2,1.5,Ensemble
1,1.0,Région de Tanger-Tétouan-Al Hoceima,4008655,1048860,3.8,1047295,0.9,16.1,66.3,1,...,6.5,25.7,2.2,97.7,0.4,0.3,1.4,0.1,2.3,Ensemble
2,1511.0,Préfecture de Tanger-Assilah,1487236,418844,3.6,418108,1.4,25.1,70.2,0.7,...,9,3.4,0.9,99.3,0.5,0,0.1,0.1,0.8,Ensemble
3,1511010.0,Commune de Tanger,1272718,362062,3.5,361404,1.5,25.6,71.7,0.4,...,9.2,0.3,0.4,99.3,0.6,0,0,0.1,…,Ensemble
4,15110105.0,Arrondissement de Mghogha,252177,70679,3.6,70596,2,14.9,82.1,0.3,...,17.2,0.7,0.4,99.4,0.4,0,0,0.1,…,Ensemble
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6046,1206603.0,Cercle d'Aousserd,565,2010,3.6,502,0,8.2,18.5,55,...,0,74.5,1.6,100,0,0,0,0,4.8,Rural
6047,120660305.0,Commune d'Aousserd,106,273,2.6,51,0,27.5,54.9,3.9,...,0,13.7,2,100,0,0,0,0,1.1,Rural
6048,120660303.0,Commune d'Aghouinite*,263,1006,3.8,263,.,.,.,.,...,.,.,.,.,.,.,.,.,.,Rural
6049,120660309.0,Commune de Zoug*,155,592,3.8,155,.,.,.,.,...,.,.,.,.,.,.,.,.,.,Rural
6050,120660307.0,Commune de Tichla,41,139,3.4,33,0,0,42.4,3,...,0,100,0,100,0,0,0,0,45,Rural

In [ ]:
# Nettoyage des codes géographiques (suppression des .0)
def clean_code_geo(df):
    df = df.copy()
    df['Code_geographique'] = df['Code_geographique'].astype(str).str.replace('.0', '', regex=False)
    return df

population_all = clean_code_geo(population_all)
menages_all = clean_code_geo(menages_all)

In [ ]:
population_all

,Code_geographique,Collectivites_territoriales,Sexe : Ensemble_Population légale,Sexe : Ensemble_Population municipale,Sexe : Ensemble_Sexe (%)_Masculin,Sexe : Ensemble_Sexe (%)_Féminin,Sexe : Ensemble_Âge quinquennal (%)_0-4 ans,Sexe : Ensemble_Âge quinquennal (%)_5-9 ans,Sexe : Ensemble_Âge quinquennal (%)_10-14 ans,Sexe : Ensemble_Âge quinquennal (%)_15-19 ans,...,Sexe : Féminin_Population active occupée de 15 ans et plus,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Employeur,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Indépendant,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur public,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur privé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Aide familial,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Apprenti,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Coopérateur/Associé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Autre,Milieu
0,nan,Ensemble du territoire national,36828330,36490591,49.9,50.1,7.6,9.3,9.6,8.2,...,1696785,1.7,11.2,21.7,58.8,2.8,0.4,0.9,2.4,Ensemble
1,1,Région de Tanger-Tétouan-Al Hoceima,4030222,4008655,50.8,49.2,8.2,9.6,9.4,7.9,...,232294,1.3,11.3,15.4,62.3,7,0.3,0.9,1.6,Ensemble
2,1511,Préfecture de Tanger-Assilah,1494413,1487236,50.8,49.2,8.5,9.4,8.8,7.4,...,127760,1.5,7.4,10.5,77.1,1.3,0.3,0.7,1.3,Ensemble
3,1511010,Commune de Tanger,1275428,1272718,50.6,49.4,8.3,9.2,8.6,7.4,...,114125,1.5,6.8,10.4,78.4,0.7,0.3,0.7,1.3,Ensemble
4,15110105,Arrondissement de Mghogha,252656,252177,50.8,49.2,8.2,9.3,9,7.6,...,21357,1.4,6.5,7.7,81.2,0.7,0.2,0.7,1.6,Ensemble
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6046,1206603,Cercle d'Aousserd,12188,2010,56,44,9.4,10,8.8,6.9,...,97,1,9.3,17.5,62.9,6.2,0,0,3.1,Rural
6047,120660305,Commune d'Aousserd,3855,273,76.2,23.8,3.3,2.6,6.2,2.6,...,9,0,11.1,22.2,0,55.6,0,0,11.1,Rural
6048,120660303,Commune d'Aghouinite*,1006,1006,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,Rural
6049,120660309,Commune de Zoug*,592,592,.,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,Rural
6050,120660307,Commune de Tichla,6735,139,57.6,42.4,17.3,12.2,7.9,6.5,...,1,0,0,100,0,0,0,0,0,Rural

In [ ]:
def filter_regions_and_total(df):
    return df[
        (df['Collectivites_territoriales'] == 'Ensemble du territoire national') |
        (df['Code_geographique'].str.match(r'^\d{1,2}$', na=False))  # Ex : 1, 11
    ]

population_regions = filter_regions_and_total(population_all)
menages_regions = filter_regions_and_total(menages_all)

In [ ]:
population_regions

,Code_geographique,Collectivites_territoriales,Sexe : Ensemble_Population légale,Sexe : Ensemble_Population municipale,Sexe : Ensemble_Sexe (%)_Masculin,Sexe : Ensemble_Sexe (%)_Féminin,Sexe : Ensemble_Âge quinquennal (%)_0-4 ans,Sexe : Ensemble_Âge quinquennal (%)_5-9 ans,Sexe : Ensemble_Âge quinquennal (%)_10-14 ans,Sexe : Ensemble_Âge quinquennal (%)_15-19 ans,...,Sexe : Féminin_Population active occupée de 15 ans et plus,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Employeur,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Indépendant,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur public,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur privé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Aide familial,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Apprenti,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Coopérateur/Associé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Autre,Milieu
0,nan,Ensemble du territoire national,36828330,36490591,49.9,50.1,7.6,9.3,9.6,8.2,...,1696785,1.7,11.2,21.7,58.8,2.8,0.4,0.9,2.4,Ensemble
1,1,Région de Tanger-Tétouan-Al Hoceima,4030222,4008655,50.8,49.2,8.2,9.6,9.4,7.9,...,232294,1.3,11.3,15.4,62.3,7,0.3,0.9,1.6,Ensemble
204,2,Région de l'Oriental,2294665,2269378,48.9,51.1,6.8,8.9,9.5,7.8,...,67918,1.5,12.3,35,45.3,1.9,0.4,1,2.7,Ensemble
373,3,Région de Fès-Meknès,4467911,4436873,49.7,50.3,7.6,9.2,9.7,8.5,...,168680,1.5,12.1,24.9,54.2,3,0.6,0.9,2.7,Ensemble
641,4,Région de Rabat-Salé-Kénitra,5132639,5088656,49.7,50.3,7.5,8.9,9.2,7.9,...,315120,1.9,10.3,26.2,56,1.7,0.5,0.9,2.6,Ensemble
807,5,Région de Béni Mellal-Khénifra,2525801,2510799,48.9,51.1,7.4,9.5,10.3,8.5,...,67121,1.3,18.4,29.4,40.2,6.5,0.5,1,2.6,Ensemble
989,6,Région de Casablanca-Settat,7688967,7651096,49.9,50.1,7.4,8.8,9.1,7.8,...,486971,2.2,10.3,15.4,66.6,1.6,0.4,0.9,2.8,Ensemble
1211,7,Région de Marrakech-Safi,4892393,4864187,50.4,49.6,7.9,9.7,10.3,8.6,...,161384,2,12.3,24.9,55.7,1.5,0.5,0.9,2.2,Ensemble
1527,8,Région de Drâa-Tafilalet,1655623,1643144,49.2,50.8,8.9,10.5,11.1,8.9,...,33059,0.9,13.6,39.1,32,10.3,0.6,0.8,2.6,Ensemble
1689,9,Région de Souss-Massa,3020431,2994360,49.6,50.4,7.3,9.1,9.7,8.3,...,128130,1.2,8.8,18.6,67.7,1.3,0.4,0.7,1.4,Ensemble
1896,10,Région de Guelmim-Oued Noun,448685,417663,49.3,50.7,7.5,9.5,9.7,8,...,10716,0.8,10.4,43.5,40,1.6,0.2,1,2.5,Ensemble
1966,11,Région de Laâyoune-Sakia El Hamra,451028,419169,51,49,9,10.2,9.5,7.9,...,15664,1.3,15.4,37,40.4,1.1,0.3,1.3,3.1,Ensemble
1996,12,Région de Dakhla-Oued Ed-Dahab,219965,186611,58.4,41.6,8.9,9.1,8.2,7.3,...,9726,0.9,9.5,22.7,63.2,0.6,0,0.8,2.2,Ensemble
2017,nan,Ensemble du territoire national,23110108,22921202,49.3,50.7,7.1,8.7,9,7.8,...,1465314,1.9,10.5,22.6,60.4,0.9,0.4,0.9,2.4,Urbain
2018,1,Région de Tanger-Tétouan-Al Hoceima,2638815,2626188,50.2,49.8,7.8,9.2,9,7.6,...,191272,1.5,8.8,17,69.1,0.8,0.3,0.8,1.7,Urbain
2221,2,Région de l'Oriental,1505714,1490769,48.5,51.5,6.3,8.4,9.1,7.7,...,58999,1.7,12.3,35.9,44.7,1.4,0.4,0.9,2.7,Urbain
2390,3,Région de Fès-Meknès,2855366,2832025,49,51,7.1,8.7,9.4,8.2,...,147840,1.7,11.5,25.9,55.7,1,0.6,1,2.6,Urbain
2658,4,Région de Rabat-Salé-Kénitra,3627178,3592146,49,51,6.8,8.2,8.5,7.5,...,282301,2,10.1,28.2,55,0.9,0.4,0.8,2.6,Urbain
2824,5,Région de Béni Mellal-Khénifra,1283492,1274561,47.9,52.1,6.7,8.8,9.6,8.1,...,49770,1.7,18.4,32.7,41.1,1.8,0.5,0.9,2.9,Urbain
3006,6,Région de Casablanca-Settat,5633748,5605153,49.3,50.7,6.9,8.2,8.6,7.5,...,446450,2.3,9.7,15.5,67.7,0.9,0.4,0.9,2.7,Urbain
3228,7,Région de Marrakech-Safi,2248954,2234502,49.1,50.9,7,8.7,9.4,8.2,...,132194,2.1,11.5,25.8,56.4,0.8,0.5,0.9,2,Urbain
3544,8,Région de Drâa-Tafilalet,607724,599324,48.9,51.1,8.2,9.9,10.6,8.7,...,19162,1.1,11.2,45.2,37.1,1.4,0.5,0.7,2.6,Urbain
3706,9,Région de Souss-Massa,1816102,1796534,49.9,50.1,7.1,9,9.5,8.4,...,102979,1.4,9.2,19.4,66.8,0.7,0.4,0.6,1.4,Urbain
3913,10,Région de Guelmim-Oued Noun,299543,294894,49.5,50.5,7.8,9.7,9.8,8,...,9482,0.8,10.8,42.3,41,1.3,0.2,1,2.7,Urbain
3983,11,Région de Laâyoune-Sakia El Hamra,416636,407705,50.9,49.1,9,10.2,9.6,7.9,...,15462,1.3,15.4,36.9,40.6,1.1,0.3,1.3,3.1,Urbain
4013,12,Région de Dakhla-Oued Ed-Dahab,176836,167401,54.7,45.3,9.7,9.9,8.9,7.4,...,9402,1,9.6,23,62.7,0.5,0.1,0.8,2.2,Urbain
4034,nan,Ensemble du territoire national,13718222,13569389,50.8,49.2,8.6,10.3,10.7,8.7,...,231470,0.8,15.8,15.9,48.8,14.8,0.5,1,2.4,Rural
4035,1,Région de Tanger-Tétouan-Al Hoceima,1391407,1382467,51.9,48.1,8.8,10.2,10.2,8.6,...,41022,0.4,22.7,8.2,30.7,35.6,0.1,1.4,0.9,Rural
4238,2,Région de l'Oriental,788951,778609,49.6,50.4,7.7,9.9,10.1,8.2,...,8919,0.8,12.3,28.5,49.2,5.3,0.3,1,2.7,Rural
4407,3,Région de Fès-Meknès,1612545,1604848,50.9,49.1,8.6,10,10.4,8.8,...,20840,0.5,16.5,17.5,44,17.2,0.7,0.7,2.9,Rural
4675,4,Région de Rabat-Salé-Kénitra,1505461,1496510,51.2,48.8,9.3,10.7,10.9,8.9,...,32819,1.4,11.8,9.4,64.3,8.7,0.7,1.1,2.7,Rural
4841,5,Région de Béni Mellal-Khénifra,1242309,1236238,49.9,50.1,8.1,10.1,10.9,8.8,...,17351,0.4,18.4,19.9,37.8,20,0.6,1,1.9,Rural
5023,6,Région de Casablanca-Settat,2055219,2045943,51.4,48.6,8.9,10.5,10.7,8.6,...,40521,1.3,16.1,14.3,53.9,9.1,0.4,1,3.9,Rural
5245,7,Région de Marrakech-Safi,2643439,2629685,51.6,48.4,8.7,10.6,11.1,9,...,29190,1.2,15.9,20.8,52.4,5,0.7,0.9,3.1,Rural
5561,8,Région de Drâa-Tafilalet,1047899,1043820,49.4,50.6,9.3,10.8,11.3,9,...,13897,0.5,17,30.7,24.9,22.6,0.8,1,2.5,Rural
5723,9,Région de Souss-Massa,1204329,1197826,49.1,50.9,7.4,9.1,9.8,8.2,...,25151,0.3,7.4,15.3,71.3,3.4,0.3,0.9,1,Rural
5930,10,Région de Guelmim-Oued Noun,149142,122769,48.7,51.3,6.7,9,9.4,8,...,1234,0.3,7.1,53.4,33,3.7,0.2,0.9,1.4,Rural
6000,11,Région de Laâyoune-Sakia El Hamra,34392,11464,57.9,42.1,7.4,8,6.7,6.2,...,202,1.5,12.9,48,28.7,7.9,0,0,1,Rural
6030,12,Région de Dakhla-Oued Ed-Dahab,43129,19210,90.8,9.2,1.8,1.7,1.6,6,...,324,0.3,4.9,12,78,3.9,0,0,0.9,Rural

In [ ]:
population_regions.loc[population_regions['Code_geographique'] == 'nan', 'Code_geographique'] = 0

In [ ]:
menages_regions.loc[menages_regions['Code_geographique'] == 'nan', 'Code_geographique'] = 0
menages_regions

,Code_geographique,Collectivites_territoriales,Population municipale_Pop_municipale,Ménages_Ménages population,Taille moyenne des ménages_Taille moyenne,Ménages sédentaires,Type de logement (%)_Villa / Étage de villa,Type de logement (%)_Appartement,Type de logement (%)_Maison marocaine,Type de logement (%)_Maison sommaire / Bidonville,...,Mode d’évacuation des déchets ménagers (%)_Camion de la commune / Camion privé,Mode d’évacuation des déchets ménagers (%)_Dans la nature,Mode d’évacuation des déchets ménagers (%)_Autre,Combustible de cuisson utilisé (%)_Gaz,Combustible de cuisson utilisé (%)_Électricité,Combustible de cuisson utilisé (%)_Charbon,Combustible de cuisson utilisé (%)_Bois énergie,Combustible de cuisson utilisé (%)_Autre,Distance moyenne des logements à la route goudronnée (Km),Milieu
0,0,Ensemble du territoire national,36490591,9275038,3.9,9263270,1.9,16.6,58.8,3,...,15,26.6,1.9,95.2,0.4,0.2,4,0.2,1.5,Ensemble
1,1,Région de Tanger-Tétouan-Al Hoceima,4008655,1048860,3.8,1047295,0.9,16.1,66.3,1,...,6.5,25.7,2.2,97.7,0.4,0.3,1.4,0.1,2.3,Ensemble
204,2,Région de l'Oriental,2269378,575015,3.9,574253,1.4,6,75.5,0.9,...,21.2,25.1,1.8,95.8,0.3,0.1,3.7,0.3,2,Ensemble
373,3,Région de Fès-Meknès,4436873,1135717,3.9,1134623,1.5,14.7,58.1,2.8,...,13.8,29,1.4,95.7,0.3,0.1,3.7,0.2,1.9,Ensemble
641,4,Région de Rabat-Salé-Kénitra,5088656,1301492,3.9,1300546,2.7,23.1,57.3,3.4,...,16.8,22.3,1.4,97.5,0.5,0.3,1.5,0.2,1,Ensemble
807,5,Région de Béni Mellal-Khénifra,2510799,616566,4.1,615888,1.4,2.4,73.5,1.3,...,16.3,35.5,1.3,90,0.2,0.2,9.3,0.3,1.4,Ensemble
989,6,Région de Casablanca-Settat,7651096,2021032,3.8,2019042,3.1,32.7,42,7.5,...,7.9,18.1,1.3,98.3,0.6,0.1,0.8,0.2,1.1,Ensemble
1211,7,Région de Marrakech-Safi,4864187,1185865,4.1,1184882,2.1,9.4,53.1,1.6,...,10.8,42.2,2.6,91.1,0.4,0.2,8,0.3,1.6,Ensemble
1527,8,Région de Drâa-Tafilalet,1643144,338977,4.8,337245,0.8,1.3,56.5,0.2,...,31.9,33.3,3.4,85.4,0.2,0.3,13.9,0.2,1.5,Ensemble
1689,9,Région de Souss-Massa,2994360,785208,3.8,784347,1.2,8.1,74.5,0.6,...,33.8,25.9,4.4,92.1,0.3,0.3,7.1,0.2,1.1,Ensemble
1896,10,Région de Guelmim-Oued Noun,417663,105394,4.0,104597,0.3,1.1,80.5,0.3,...,26.9,22.5,1,95.2,0.2,0.3,4.2,0.1,1.3,Ensemble
1966,11,Région de Laâyoune-Sakia El Hamra,419169,106751,3.9,106625,0.6,10.6,83.6,3,...,24.1,2.1,0.6,99.3,0.5,0,0.1,0.1,2,Ensemble
1996,12,Région de Dakhla-Oued Ed-Dahab,186611,54161,3.4,53927,0.6,11.9,72.6,6.2,...,14.9,9.3,1.2,97.1,2.6,0,0,0.3,2.2,Ensemble
2017,0,Ensemble du territoire national,22921202,6173930,3.7,6166796,2.7,24.4,68,3.3,...,18.4,2,0.7,99.2,0.5,0,0.2,0.1,…,Urbain
2018,1,Région de Tanger-Tétouan-Al Hoceima,2626188,728766,3.6,727486,1.2,23,73.6,1.1,...,8.4,1.3,0.6,99.4,0.5,0,0,0.1,…,Urbain
2221,2,Région de l'Oriental,1490769,390123,3.8,389673,1.9,8.4,87.4,0.6,...,25.7,2.7,0.5,99.4,0.3,0,0.2,0.1,…,Urbain
2390,3,Région de Fès-Meknès,2832025,755719,3.7,754953,2.1,21.6,71.5,2.9,...,17.6,2.4,0.8,99.4,0.3,0,0.2,0.1,…,Urbain
2658,4,Région de Rabat-Salé-Kénitra,3592146,984650,3.6,983868,3.3,30.3,62.4,2.7,...,21.2,2,0.6,99.2,0.6,0,0.1,0.1,…,Urbain
2824,5,Région de Béni Mellal-Khénifra,1274561,338559,3.8,338131,2.3,4.1,90.8,1.5,...,22,1.9,0.3,99.4,0.2,0,0.3,0.1,…,Urbain
3006,6,Région de Casablanca-Settat,5605153,1554705,3.6,1552864,3.8,41,46,7.6,...,9.2,1.7,0.5,99.2,0.7,0,0,0.1,…,Urbain
3228,7,Région de Marrakech-Safi,2234502,581558,3.8,580930,3.6,18.3,73.6,2.2,...,14.6,2.9,0.9,99,0.5,0,0.3,0.1,…,Urbain
3544,8,Région de Drâa-Tafilalet,599324,139655,4.3,139447,1.7,2.7,86.9,0.2,...,44.4,2.9,0.5,98.3,0.2,0.1,1.3,0.1,…,Urbain
3706,9,Région de Souss-Massa,1796534,476722,3.8,476195,1.7,13.1,83.3,0.7,...,43.7,1.9,1.6,99.1,0.4,0.1,0.3,0.1,…,Urbain
3913,10,Région de Guelmim-Oued Noun,294894,73720,4,73630,0.3,1.5,97,0.2,...,36.9,1.1,0.6,99.3,0.2,0.1,0.3,0.1,…,Urbain
3983,11,Région de Laâyoune-Sakia El Hamra,407705,102853,4,102805,0.5,10.8,85.1,2.5,...,24.5,0.2,0.5,99.4,0.5,0,0,0.1,…,Urbain
4013,12,Région de Dakhla-Oued Ed-Dahab,167401,46900,3.6,46814,0.5,13.6,82.8,1.1,...,13.9,2,1.3,99.5,0.3,0,0,0.2,…,Urbain
4034,0,Ensemble du territoire national,3101108,13569389,4.4,3096474,0.5,1.2,40.5,2.6,...,8.2,75.5,4.4,87.1,0.3,0.5,11.8,0.4,1.5,Rural
4035,1,Région de Tanger-Tétouan-Al Hoceima,320094,1382467,4.3,319809,0.3,0.3,49.7,0.7,...,2.1,81.1,5.8,94,0.3,1,4.5,0.2,2.3,Rural
4238,2,Région de l'Oriental,184892,778609,4.2,184580,0.5,0.8,50.4,1.5,...,11.7,72.6,4.5,88.2,0.2,0.1,11,0.5,2,Rural
4407,3,Région de Fès-Meknès,379998,1604848,4.2,379670,0.4,0.9,31.4,2.8,...,6.3,81.8,2.7,88.2,0.3,0.2,10.9,0.5,1.9,Rural
4675,4,Région de Rabat-Salé-Kénitra,316842,1496510,4.7,316678,0.6,0.8,41.2,5.6,...,3.3,85.4,3.7,92.4,0.3,0.9,6,0.3,1,Rural
4841,5,Région de Béni Mellal-Khénifra,278007,1236238,4.4,277757,0.4,0.3,52.4,1.1,...,9.5,76.3,2.6,78.6,0.2,0.5,20.3,0.4,1.4,Rural
5023,6,Région de Casablanca-Settat,466327,2045943,4.4,466178,0.9,4.8,28.7,7.2,...,3.7,72.6,3.8,95.5,0.3,0.2,3.5,0.5,1.1,Rural
5245,7,Région de Marrakech-Safi,604307,2629685,4.4,603952,0.7,0.8,33.4,1,...,7.1,80,4.3,83.5,0.2,0.3,15.4,0.5,1.6,Rural
5561,8,Région de Drâa-Tafilalet,199322,1043820,5.2,197798,0.2,0.3,35.1,0.2,...,23,54.8,5.4,76.3,0.2,0.5,22.7,0.2,1.5,Rural
5723,9,Région de Souss-Massa,308486,1197826,3.9,308152,0.4,0.3,60.9,0.4,...,18.3,62.8,8.7,81.2,0.2,0.7,17.6,0.3,1.1,Rural
5930,10,Région de Guelmim-Oued Noun,31674,122769,3.9,30967,0.2,0.2,41.3,0.8,...,3.2,73.2,2,85.4,0.2,0.7,13.4,0.3,1.3,Rural
6000,11,Région de Laâyoune-Sakia El Hamra,3898,11464,2.9,3820,1.8,4,44.5,15.5,...,13.6,55.8,4.9,96.6,0.3,0.2,2.7,0.2,2,Rural
6030,12,Région de Dakhla-Oued Ed-Dahab,7261,19210,2.6,7113,0.9,0.7,5.8,40.4,...,21.3,57.2,0.6,80.9,18.1,0.1,0.2,0.7,2.2,Rural

In [ ]:
def sort_by_code_geo(df):
    df = df.copy()
    df['Code_geo_sort'] = pd.to_numeric(df['Code_geographique'], errors='coerce')
    df = df.sort_values(by='Code_geo_sort').drop(columns='Code_geo_sort')
    return df
population_regions = sort_by_code_geo(population_regions)
menages_regions = sort_by_code_geo(menages_regions)

In [ ]:
population_regions

,Code_geographique,Collectivites_territoriales,Sexe : Ensemble_Population légale,Sexe : Ensemble_Population municipale,Sexe : Ensemble_Sexe (%)_Masculin,Sexe : Ensemble_Sexe (%)_Féminin,Sexe : Ensemble_Âge quinquennal (%)_0-4 ans,Sexe : Ensemble_Âge quinquennal (%)_5-9 ans,Sexe : Ensemble_Âge quinquennal (%)_10-14 ans,Sexe : Ensemble_Âge quinquennal (%)_15-19 ans,...,Sexe : Féminin_Population active occupée de 15 ans et plus,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Employeur,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Indépendant,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur public,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur privé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Aide familial,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Apprenti,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Coopérateur/Associé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Autre,Milieu
0,0,Ensemble du territoire national,36828330,36490591,49.9,50.1,7.6,9.3,9.6,8.2,...,1696785,1.7,11.2,21.7,58.8,2.8,0.4,0.9,2.4,Ensemble
2017,0,Ensemble du territoire national,23110108,22921202,49.3,50.7,7.1,8.7,9,7.8,...,1465314,1.9,10.5,22.6,60.4,0.9,0.4,0.9,2.4,Urbain
4034,0,Ensemble du territoire national,13718222,13569389,50.8,49.2,8.6,10.3,10.7,8.7,...,231470,0.8,15.8,15.9,48.8,14.8,0.5,1,2.4,Rural
2018,1,Région de Tanger-Tétouan-Al Hoceima,2638815,2626188,50.2,49.8,7.8,9.2,9,7.6,...,191272,1.5,8.8,17,69.1,0.8,0.3,0.8,1.7,Urbain
4035,1,Région de Tanger-Tétouan-Al Hoceima,1391407,1382467,51.9,48.1,8.8,10.2,10.2,8.6,...,41022,0.4,22.7,8.2,30.7,35.6,0.1,1.4,0.9,Rural
1,1,Région de Tanger-Tétouan-Al Hoceima,4030222,4008655,50.8,49.2,8.2,9.6,9.4,7.9,...,232294,1.3,11.3,15.4,62.3,7,0.3,0.9,1.6,Ensemble
204,2,Région de l'Oriental,2294665,2269378,48.9,51.1,6.8,8.9,9.5,7.8,...,67918,1.5,12.3,35,45.3,1.9,0.4,1,2.7,Ensemble
2221,2,Région de l'Oriental,1505714,1490769,48.5,51.5,6.3,8.4,9.1,7.7,...,58999,1.7,12.3,35.9,44.7,1.4,0.4,0.9,2.7,Urbain
4238,2,Région de l'Oriental,788951,778609,49.6,50.4,7.7,9.9,10.1,8.2,...,8919,0.8,12.3,28.5,49.2,5.3,0.3,1,2.7,Rural
2390,3,Région de Fès-Meknès,2855366,2832025,49,51,7.1,8.7,9.4,8.2,...,147840,1.7,11.5,25.9,55.7,1,0.6,1,2.6,Urbain
373,3,Région de Fès-Meknès,4467911,4436873,49.7,50.3,7.6,9.2,9.7,8.5,...,168680,1.5,12.1,24.9,54.2,3,0.6,0.9,2.7,Ensemble
4407,3,Région de Fès-Meknès,1612545,1604848,50.9,49.1,8.6,10,10.4,8.8,...,20840,0.5,16.5,17.5,44,17.2,0.7,0.7,2.9,Rural
2658,4,Région de Rabat-Salé-Kénitra,3627178,3592146,49,51,6.8,8.2,8.5,7.5,...,282301,2,10.1,28.2,55,0.9,0.4,0.8,2.6,Urbain
4675,4,Région de Rabat-Salé-Kénitra,1505461,1496510,51.2,48.8,9.3,10.7,10.9,8.9,...,32819,1.4,11.8,9.4,64.3,8.7,0.7,1.1,2.7,Rural
641,4,Région de Rabat-Salé-Kénitra,5132639,5088656,49.7,50.3,7.5,8.9,9.2,7.9,...,315120,1.9,10.3,26.2,56,1.7,0.5,0.9,2.6,Ensemble
807,5,Région de Béni Mellal-Khénifra,2525801,2510799,48.9,51.1,7.4,9.5,10.3,8.5,...,67121,1.3,18.4,29.4,40.2,6.5,0.5,1,2.6,Ensemble
4841,5,Région de Béni Mellal-Khénifra,1242309,1236238,49.9,50.1,8.1,10.1,10.9,8.8,...,17351,0.4,18.4,19.9,37.8,20,0.6,1,1.9,Rural
2824,5,Région de Béni Mellal-Khénifra,1283492,1274561,47.9,52.1,6.7,8.8,9.6,8.1,...,49770,1.7,18.4,32.7,41.1,1.8,0.5,0.9,2.9,Urbain
989,6,Région de Casablanca-Settat,7688967,7651096,49.9,50.1,7.4,8.8,9.1,7.8,...,486971,2.2,10.3,15.4,66.6,1.6,0.4,0.9,2.8,Ensemble
3006,6,Région de Casablanca-Settat,5633748,5605153,49.3,50.7,6.9,8.2,8.6,7.5,...,446450,2.3,9.7,15.5,67.7,0.9,0.4,0.9,2.7,Urbain
5023,6,Région de Casablanca-Settat,2055219,2045943,51.4,48.6,8.9,10.5,10.7,8.6,...,40521,1.3,16.1,14.3,53.9,9.1,0.4,1,3.9,Rural
3228,7,Région de Marrakech-Safi,2248954,2234502,49.1,50.9,7,8.7,9.4,8.2,...,132194,2.1,11.5,25.8,56.4,0.8,0.5,0.9,2,Urbain
5245,7,Région de Marrakech-Safi,2643439,2629685,51.6,48.4,8.7,10.6,11.1,9,...,29190,1.2,15.9,20.8,52.4,5,0.7,0.9,3.1,Rural
1211,7,Région de Marrakech-Safi,4892393,4864187,50.4,49.6,7.9,9.7,10.3,8.6,...,161384,2,12.3,24.9,55.7,1.5,0.5,0.9,2.2,Ensemble
1527,8,Région de Drâa-Tafilalet,1655623,1643144,49.2,50.8,8.9,10.5,11.1,8.9,...,33059,0.9,13.6,39.1,32,10.3,0.6,0.8,2.6,Ensemble
5561,8,Région de Drâa-Tafilalet,1047899,1043820,49.4,50.6,9.3,10.8,11.3,9,...,13897,0.5,17,30.7,24.9,22.6,0.8,1,2.5,Rural
3544,8,Région de Drâa-Tafilalet,607724,599324,48.9,51.1,8.2,9.9,10.6,8.7,...,19162,1.1,11.2,45.2,37.1,1.4,0.5,0.7,2.6,Urbain
3706,9,Région de Souss-Massa,1816102,1796534,49.9,50.1,7.1,9,9.5,8.4,...,102979,1.4,9.2,19.4,66.8,0.7,0.4,0.6,1.4,Urbain
5723,9,Région de Souss-Massa,1204329,1197826,49.1,50.9,7.4,9.1,9.8,8.2,...,25151,0.3,7.4,15.3,71.3,3.4,0.3,0.9,1,Rural
1689,9,Région de Souss-Massa,3020431,2994360,49.6,50.4,7.3,9.1,9.7,8.3,...,128130,1.2,8.8,18.6,67.7,1.3,0.4,0.7,1.4,Ensemble
1896,10,Région de Guelmim-Oued Noun,448685,417663,49.3,50.7,7.5,9.5,9.7,8,...,10716,0.8,10.4,43.5,40,1.6,0.2,1,2.5,Ensemble
3913,10,Région de Guelmim-Oued Noun,299543,294894,49.5,50.5,7.8,9.7,9.8,8,...,9482,0.8,10.8,42.3,41,1.3,0.2,1,2.7,Urbain
5930,10,Région de Guelmim-Oued Noun,149142,122769,48.7,51.3,6.7,9,9.4,8,...,1234,0.3,7.1,53.4,33,3.7,0.2,0.9,1.4,Rural
6000,11,Région de Laâyoune-Sakia El Hamra,34392,11464,57.9,42.1,7.4,8,6.7,6.2,...,202,1.5,12.9,48,28.7,7.9,0,0,1,Rural
1966,11,Région de Laâyoune-Sakia El Hamra,451028,419169,51,49,9,10.2,9.5,7.9,...,15664,1.3,15.4,37,40.4,1.1,0.3,1.3,3.1,Ensemble
3983,11,Région de Laâyoune-Sakia El Hamra,416636,407705,50.9,49.1,9,10.2,9.6,7.9,...,15462,1.3,15.4,36.9,40.6,1.1,0.3,1.3,3.1,Urbain
4013,12,Région de Dakhla-Oued Ed-Dahab,176836,167401,54.7,45.3,9.7,9.9,8.9,7.4,...,9402,1,9.6,23,62.7,0.5,0.1,0.8,2.2,Urbain
1996,12,Région de Dakhla-Oued Ed-Dahab,219965,186611,58.4,41.6,8.9,9.1,8.2,7.3,...,9726,0.9,9.5,22.7,63.2,0.6,0,0.8,2.2,Ensemble
6030,12,Région de Dakhla-Oued Ed-Dahab,43129,19210,90.8,9.2,1.8,1.7,1.6,6,...,324,0.3,4.9,12,78,3.9,0,0,0.9,Rural

In [ ]:
population_regions

,Code_geographique,Collectivites_territoriales,Sexe : Ensemble_Population légale,Sexe : Ensemble_Population municipale,Sexe : Ensemble_Sexe (%)_Masculin,Sexe : Ensemble_Sexe (%)_Féminin,Sexe : Ensemble_Âge quinquennal (%)_0-4 ans,Sexe : Ensemble_Âge quinquennal (%)_5-9 ans,Sexe : Ensemble_Âge quinquennal (%)_10-14 ans,Sexe : Ensemble_Âge quinquennal (%)_15-19 ans,...,Sexe : Féminin_Population active occupée de 15 ans et plus,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Employeur,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Indépendant,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur public,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Salarié du secteur privé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Aide familial,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Apprenti,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Coopérateur/Associé,Sexe : Féminin_Statut professionnel des actifs occupés de 15 ans et plus (%)_Autre,Milieu
0,0,Ensemble du territoire national,36828330,36490591,49.9,50.1,7.6,9.3,9.6,8.2,...,1696785,1.7,11.2,21.7,58.8,2.8,0.4,0.9,2.4,Ensemble
2017,0,Ensemble du territoire national,23110108,22921202,49.3,50.7,7.1,8.7,9,7.8,...,1465314,1.9,10.5,22.6,60.4,0.9,0.4,0.9,2.4,Urbain
4034,0,Ensemble du territoire national,13718222,13569389,50.8,49.2,8.6,10.3,10.7,8.7,...,231470,0.8,15.8,15.9,48.8,14.8,0.5,1,2.4,Rural
2018,1,Région de Tanger-Tétouan-Al Hoceima,2638815,2626188,50.2,49.8,7.8,9.2,9,7.6,...,191272,1.5,8.8,17,69.1,0.8,0.3,0.8,1.7,Urbain
4035,1,Région de Tanger-Tétouan-Al Hoceima,1391407,1382467,51.9,48.1,8.8,10.2,10.2,8.6,...,41022,0.4,22.7,8.2,30.7,35.6,0.1,1.4,0.9,Rural
1,1,Région de Tanger-Tétouan-Al Hoceima,4030222,4008655,50.8,49.2,8.2,9.6,9.4,7.9,...,232294,1.3,11.3,15.4,62.3,7,0.3,0.9,1.6,Ensemble
204,2,Région de l'Oriental,2294665,2269378,48.9,51.1,6.8,8.9,9.5,7.8,...,67918,1.5,12.3,35,45.3,1.9,0.4,1,2.7,Ensemble
2221,2,Région de l'Oriental,1505714,1490769,48.5,51.5,6.3,8.4,9.1,7.7,...,58999,1.7,12.3,35.9,44.7,1.4,0.4,0.9,2.7,Urbain
4238,2,Région de l'Oriental,788951,778609,49.6,50.4,7.7,9.9,10.1,8.2,...,8919,0.8,12.3,28.5,49.2,5.3,0.3,1,2.7,Rural
2390,3,Région de Fès-Meknès,2855366,2832025,49,51,7.1,8.7,9.4,8.2,...,147840,1.7,11.5,25.9,55.7,1,0.6,1,2.6,Urbain
373,3,Région de Fès-Meknès,4467911,4436873,49.7,50.3,7.6,9.2,9.7,8.5,...,168680,1.5,12.1,24.9,54.2,3,0.6,0.9,2.7,Ensemble
4407,3,Région de Fès-Meknès,1612545,1604848,50.9,49.1,8.6,10,10.4,8.8,...,20840,0.5,16.5,17.5,44,17.2,0.7,0.7,2.9,Rural
2658,4,Région de Rabat-Salé-Kénitra,3627178,3592146,49,51,6.8,8.2,8.5,7.5,...,282301,2,10.1,28.2,55,0.9,0.4,0.8,2.6,Urbain
4675,4,Région de Rabat-Salé-Kénitra,1505461,1496510,51.2,48.8,9.3,10.7,10.9,8.9,...,32819,1.4,11.8,9.4,64.3,8.7,0.7,1.1,2.7,Rural
641,4,Région de Rabat-Salé-Kénitra,5132639,5088656,49.7,50.3,7.5,8.9,9.2,7.9,...,315120,1.9,10.3,26.2,56,1.7,0.5,0.9,2.6,Ensemble
807,5,Région de Béni Mellal-Khénifra,2525801,2510799,48.9,51.1,7.4,9.5,10.3,8.5,...,67121,1.3,18.4,29.4,40.2,6.5,0.5,1,2.6,Ensemble
4841,5,Région de Béni Mellal-Khénifra,1242309,1236238,49.9,50.1,8.1,10.1,10.9,8.8,...,17351,0.4,18.4,19.9,37.8,20,0.6,1,1.9,Rural
2824,5,Région de Béni Mellal-Khénifra,1283492,1274561,47.9,52.1,6.7,8.8,9.6,8.1,...,49770,1.7,18.4,32.7,41.1,1.8,0.5,0.9,2.9,Urbain
989,6,Région de Casablanca-Settat,7688967,7651096,49.9,50.1,7.4,8.8,9.1,7.8,...,486971,2.2,10.3,15.4,66.6,1.6,0.4,0.9,2.8,Ensemble
3006,6,Région de Casablanca-Settat,5633748,5605153,49.3,50.7,6.9,8.2,8.6,7.5,...,446450,2.3,9.7,15.5,67.7,0.9,0.4,0.9,2.7,Urbain
5023,6,Région de Casablanca-Settat,2055219,2045943,51.4,48.6,8.9,10.5,10.7,8.6,...,40521,1.3,16.1,14.3,53.9,9.1,0.4,1,3.9,Rural
3228,7,Région de Marrakech-Safi,2248954,2234502,49.1,50.9,7,8.7,9.4,8.2,...,132194,2.1,11.5,25.8,56.4,0.8,0.5,0.9,2,Urbain
5245,7,Région de Marrakech-Safi,2643439,2629685,51.6,48.4,8.7,10.6,11.1,9,...,29190,1.2,15.9,20.8,52.4,5,0.7,0.9,3.1,Rural
1211,7,Région de Marrakech-Safi,4892393,4864187,50.4,49.6,7.9,9.7,10.3,8.6,...,161384,2,12.3,24.9,55.7,1.5,0.5,0.9,2.2,Ensemble
1527,8,Région de Drâa-Tafilalet,1655623,1643144,49.2,50.8,8.9,10.5,11.1,8.9,...,33059,0.9,13.6,39.1,32,10.3,0.6,0.8,2.6,Ensemble
5561,8,Région de Drâa-Tafilalet,1047899,1043820,49.4,50.6,9.3,10.8,11.3,9,...,13897,0.5,17,30.7,24.9,22.6,0.8,1,2.5,Rural
3544,8,Région de Drâa-Tafilalet,607724,599324,48.9,51.1,8.2,9.9,10.6,8.7,...,19162,1.1,11.2,45.2,37.1,1.4,0.5,0.7,2.6,Urbain
3706,9,Région de Souss-Massa,1816102,1796534,49.9,50.1,7.1,9,9.5,8.4,...,102979,1.4,9.2,19.4,66.8,0.7,0.4,0.6,1.4,Urbain
5723,9,Région de Souss-Massa,1204329,1197826,49.1,50.9,7.4,9.1,9.8,8.2,...,25151,0.3,7.4,15.3,71.3,3.4,0.3,0.9,1,Rural
1689,9,Région de Souss-Massa,3020431,2994360,49.6,50.4,7.3,9.1,9.7,8.3,...,128130,1.2,8.8,18.6,67.7,1.3,0.4,0.7,1.4,Ensemble
1896,10,Région de Guelmim-Oued Noun,448685,417663,49.3,50.7,7.5,9.5,9.7,8,...,10716,0.8,10.4,43.5,40,1.6,0.2,1,2.5,Ensemble
3913,10,Région de Guelmim-Oued Noun,299543,294894,49.5,50.5,7.8,9.7,9.8,8,...,9482,0.8,10.8,42.3,41,1.3,0.2,1,2.7,Urbain
5930,10,Région de Guelmim-Oued Noun,149142,122769,48.7,51.3,6.7,9,9.4,8,...,1234,0.3,7.1,53.4,33,3.7,0.2,0.9,1.4,Rural
6000,11,Région de Laâyoune-Sakia El Hamra,34392,11464,57.9,42.1,7.4,8,6.7,6.2,...,202,1.5,12.9,48,28.7,7.9,0,0,1,Rural
1966,11,Région de Laâyoune-Sakia El Hamra,451028,419169,51,49,9,10.2,9.5,7.9,...,15664,1.3,15.4,37,40.4,1.1,0.3,1.3,3.1,Ensemble
3983,11,Région de Laâyoune-Sakia El Hamra,416636,407705,50.9,49.1,9,10.2,9.6,7.9,...,15462,1.3,15.4,36.9,40.6,1.1,0.3,1.3,3.1,Urbain
4013,12,Région de Dakhla-Oued Ed-Dahab,176836,167401,54.7,45.3,9.7,9.9,8.9,7.4,...,9402,1,9.6,23,62.7,0.5,0.1,0.8,2.2,Urbain
1996,12,Région de Dakhla-Oued Ed-Dahab,219965,186611,58.4,41.6,8.9,9.1,8.2,7.3,...,9726,0.9,9.5,22.7,63.2,0.6,0,0.8,2.2,Ensemble
6030,12,Région de Dakhla-Oued Ed-Dahab,43129,19210,90.8,9.2,1.8,1.7,1.6,6,...,324,0.3,4.9,12,78,3.9,0,0,0.9,Rural

In [ ]:
with pd.ExcelWriter("rgph2024_regions.xlsx") as writer:
    population_regions.to_excel(writer, sheet_name="Population", index=False)
    menages_regions.to_excel(writer, sheet_name="Ménages", index=False)

In [ ]:
from google.colab import files
files.download("rgph2024_regions.xlsx")